<script>
    $(document).ready(function () {
        var id = <?= isset($formData["page_id"]) ? $formData["page_id"] : -1; ?>;
        $('#txtName').on('input', function () {
            var str = $(this).val();
            if (id == -1) {
                var str_slug = slugify(str);
                $('#txtKeyword').val(str_slug);
                $('#txtTitle').val(str);
                $('#txtMetaKeyword').val(str);
                $('#txtMetaDescription').val(str);
            }
        });
        $('form[name=page-form]').submit(function (event) {
            var valid = true;
            if ($('input[name=txtName]').val() == '') {
                $('.msg-name').text('Name field is required.');
                $('#txtName').addClass("border-red");
                valid = false;
            } else {
                $('.msg-name').text('');
                $('#txtName').removeClass("border-red");
            }
            if ($('input[name=txtTitle]').val() == '') {
                $('.msg-title').text('Title field is required.');
                $('#txtTitle').addClass("border-red");
                valid = false;
            } else {
                $('.msg-title').text('');
                $('#txtTitle').removeClass("border-red");
            }
            if ($('input[name=txtMetaKeyword]').val() == '') {
                $('.msg-meta-keyword').text('Meta keyword field is required.');
                $('#txtMetaKeyword').addClass("border-red");
                valid = false;
            } else {
                $('.msg-meta-keyword').text('');
                $('#txtMetaKeyword').removeClass("border-red");
            }
            if ($('input[name=txtMetaDescription]').val() == '') {
                $('.msg-meta-description').text('Meta description field is required.');
                $('#txtMetaDescription').addClass("border-red");
                valid = false;
            } else {
                $('.msg-meta-description').text('');
                $('#txtMetaDescription').removeClass("border-red");
            }
            if ($('input[name=txtKeyword]').val() == '') {
                $('.msg-keyword').text('Keyword field is required.');
                $('#txtKeyword').addClass("border-red");
                valid = false;
            } else {
                $('.msg-keyword').text('');
                $('#txtKeyword').removeClass("border-red");
            }
            if ($('input[name=txtOrder]').val() == '') {
                $('.msg-order').text('Order field is required.');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else if (isNaN($('input[name=txtOrder]').val())) {
                $('.msg-order').text('Enter a valid order.');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else {
                $('.msg-order').text('');
                $('#txtOrder').removeClass("border-red");
            }
            if (!valid) event.preventDefault();
            if (valid) {
                $('button[name=sbmType]').prop('disabled', true);
            }
        });
    });
</script>
<div class="page-title">
    <div class="title_left">
        <h3 class="type-title">Register Page</h3>
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2 class="form_title"></h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br/>
                <form name="page-form" id="page-form" data-parsley-validate
                      class="form-horizontal form-label-left" method="post">
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Name<span
                                    class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255"
                                   value="<?php echo isset($formData["page_name"]) ? $formData["page_name"] : "" ?>"
                                   type="text" id="txtName" name="txtName"
                                   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["page_name"])) ? $messages["status"] : ""; ?>">
                            <span class="text-danger msg-name"><?php echo isset($messages["page_name"]) ? $messages["page_name"] : ""; ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Title <span
                                    class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input value="<?php echo isset($formData["page_title"]) ? $formData["page_title"] : "" ?>"
                                   type="text" id="txtTitle" name="txtTitle"
                                   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["page_title"])) ? $messages["status"] : ""; ?>">
                            <span class="text-danger msg-title"><?php echo isset($messages["page_title"]) ? $messages["page_title"] : ""; ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Keyword <span
                                    class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input value="<?php echo isset($formData["page_keyword"]) ? $formData["page_keyword"] : "" ?>"
                                   type="text" id="txtKeyword" name="txtKeyword"
                                   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["page_keyword"])) ? $messages["status"] : ""; ?>">
                            <span class="text-danger msg-keyword"><?php echo isset($messages["page_keyword"]) ? $messages["page_keyword"] : ""; ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Meta Keyword <span
                                    class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input value="<?php echo isset($formData["page_meta_keyword"]) ? $formData["page_meta_keyword"] : "" ?>"
                                   type="text" id="txtMetaKeyword" name="txtMetaKeyword"
                                   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["page_meta_keyword"])) ? $messages["status"] : ""; ?>">
                            <span class="text-danger msg-meta-keyword"><?php echo isset($messages["page_meta_keyword"]) ? $messages["page_meta_keyword"] : ""; ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Meta Description <span
                                    class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input value="<?php echo isset($formData["page_meta_description"]) ? $formData["page_meta_description"] : "" ?>"
                                   type="text" id="txtMetaDescription" name="txtMetaDescription"
                                   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["page_meta_description"])) ? $messages["status"] : ""; ?>">
                            <span class="text-danger msg-meta-description"><?php echo isset($messages["page_meta_description"]) ? $messages["page_meta_description"] : ""; ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="country-code">Language </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <select id="slcLang" name="slcLang" class="form-control col-md-7 col-xs-12">
                                <option value="">Select Language...</option>
                                <?php
                                echo isset($select_lang) ? $select_lang : "";
                                ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Domain
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input
                                    value="<?php echo isset($formData["page_domain"]) ? $formData["page_domain"] : "" ?>"
                                    type="text" id="txtDomain" name="txtDomain"
                                    class="form-control col-md-7 col-xs-12 ">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Meta Image
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input placeholder="1920 x 960"
                                    value="<?php echo isset($formData["page_meta_image"]) ? $formData["page_meta_image"] : "" ?>"
                                    type="text" id="txtMetaImage" name="txtMetaImage"
                                    class="form-control col-md-7 col-xs-12 ">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Gtm
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input
                                    value="<?php echo isset($formData["page_gtm"]) ? $formData["page_gtm"] : "" ?>"
                                    type="text" id="txtGtm" name="txtGtm"
                                    class="form-control col-md-7 col-xs-12 ">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Order <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($formData["page_order"]) ? $formData["page_order"] : "" ?>" id="txtOrder" name="txtOrder" class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["order"])) ? $messages["status"] : ""; ?>" type="text">
                            <span class="text-danger msg-order"><?php echo isset($messages["order"]) ? $messages["order"] : ""; ?></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Default</label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radDefault"
                                                                  value="Y" <?php echo (isset($formData["page_default"]) && $formData["page_default"] == "Y") ? "checked" : ''; ?>>Yes<span
                                        class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radDefault"
                                                                  value="N" <?php echo (isset($formData["page_default"]) && $formData["page_default"] == "N") ? "checked" : ''; ?>>No<span
                                        class="checkmark"></span></label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Active</label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radActive"
                                                                  value="Y" <?php echo (isset($formData["page_active"]) && $formData["page_active"] == "Y") ? "checked" : ''; ?>>Yes<span
                                        class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radActive"
                                                                  value="N" <?php echo (isset($formData["page_active"]) && $formData["page_active"] == "N") ? "checked" : ''; ?>>No<span
                                        class="checkmark"></span></label>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtStyle">Style </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea class="form-control" id="txtStyle" name="txtStyle"
                                      style="height: 212px;"><?php echo isset($formData["page_style"]) ? $formData["page_style"] : ""; ?></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtStyle">Content </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea class="form-control" id="txtContent" name="txtContent"
                                      style="height: 212px;"><?php echo isset($formData["page_content"]) ? $formData["page_content"] : ""; ?></textarea>
                        </div>
                    </div>

                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button name="submit" type="submit" class="btn btn-success">Save change</button>
                            <a class="btn btn-primary" href="list-register-page">Cancel</a>
                        </div>
                    </div>
                    <?php /*
                    <script type="text/javascript">
                        window.onload = function()
                        {
                            var oFCKeditor2 = new FCKeditor('txtContent') ;
                            oFCKeditor2.Height = '500';
                            oFCKeditor2.Width = '750';
                            oFCKeditor2.ToolbarSet = "Default" ;
                            oFCKeditor2.Basepath = '../backend/fckeditor/';
                            oFCKeditor2.ReplaceTextarea() ;
                        }
                    </script>
 */ ?>
                </form>
            </div>
        </div>
    </div>
</div>