<div class="page-title">
    <div class="title_left">
        <h3 class="type-title">Office</h3>
    </div>
</div>
<?php if (!empty($messages['message'])) {
    ?>
    <div class="clearfix"></div>
    <p style="font-size:18px;text-align:center" class="alert alert-<?php echo $messages['typeMessage'] ?>">
        <?php echo $messages['message']; ?>
    </p>
<?php } ?>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">Form Edit
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br/>
                <form name="office-form" id="office-form" data-parsley-validate class="form-horizontal form-label-left"
                      method="post">
                    <input type="hidden" name="save" id="save"
                           value="<?php echo \Forexceccom\Models\ForexcecLanguage::GENERAL; ?>"/>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Country <span
                                    class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <select id="slcCountry" name="slcCountry"
                                    class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["office_country_code"])) ? $messages["status"] : ""; ?>">
                                <option value=''>Select Country ...</option>
                                <?php
                                echo isset($select_country) ? $select_country : "";
                                ?>
                            </select>
                            <span class="text-danger msg-countryCode"><?php echo isset($messages["office_country_code"]) ? $messages["office_country_code"] : ""; ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Latitude <span
                                    class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255"
                                   value="<?php echo isset($formData["office_positionX"]) ? $formData["office_positionX"] : "" ?>"
                                   id="txtPositionX" name="txtPositionX"
                                   class="form-control col-md-7 col-xs-12 <?php echo isset($messages["office_positionX"]) ? $messages["status"] : ""; ?>"
                                   type="text">
                            <span class="text-danger msg-positionX"><?php echo isset($messages["office_positionX"]) ? $messages["office_positionX"] : ""; ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Longitude <span
                                    class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255"
                                   value="<?php echo isset($formData["office_positionY"]) ? $formData["office_positionY"] : "" ?>"
                                   id="txtPositionY" name="txtPositionY"
                                   class="form-control col-md-7 col-xs-12 <?php echo isset($messages["office_positionY"]) ? $messages["status"] : ""; ?>"
                                   type="text">
                            <span class="text-danger msg-positionY"><?php echo isset($messages["office_positionY"]) ? $messages["office_positionY"] : ""; ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Phone</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255"
                                   value="<?php echo isset($formData["office_phone"]) ? $formData["office_phone"] : "" ?>"
                                   id="txtPhone" name="txtPhone" class="form-control col-md-7 col-xs-12" type="text">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Order <span
                                    class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255"
                                   value="<?php echo isset($formData["office_order"]) ? $formData["office_order"] : "" ?>"
                                   id="txtOrder" name="txtOrder"
                                   class="form-control col-md-7 col-xs-12 <?php echo isset($messages["office_order"]) ? $messages["office_order"] : ""; ?>"
                                   type="text">
                            <span class="text-danger msg-order"><?php echo isset($messages["office_order"]) ? $messages["office_order"] : ""; ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Active</label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radActive"
                                                                  value="Y" <?php echo (isset($formData["office_active"]) && $formData["office_active"] == "Y") ? "checked" : ''; ?>>Yes<span
                                        class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radActive"
                                                                  value="N" <?php echo (isset($formData["office_active"]) && $formData["office_active"] == "N") ? "checked" : ''; ?>>No<span
                                        class="checkmark"></span></label>
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button name="sbmEmployee" id="sbmEmployee" type="submit" class="btn btn-success">Save
                                change
                            </button>
                            <a class="btn btn-primary" href="<?php echo $this->url->get("/list-office"); ?>">Cancel</a>
                        </div>
                    </div>
                    <script>
                        $(document).ready(function () {
                            $('form[name=office-form').submit(function (event) {
                                valid = true;
                                if ($('select[name=slcCountry]').val() == '') {
                                    $('.msg-countryCode').text('Country Code field is required.');
                                    $('#slcCountry').addClass("border-red");
                                    valid = false;
                                } else {
                                    $('.msg-countryCode').text('');
                                    $('#slcCountry').removeClass("border-red");
                                }
                                if ($('input[name=txtPositionX]').val() == '') {
                                    $('.msg-positionX').text('Latitude field is required.');
                                    $('#txtPositionX').addClass("border-red");
                                    valid = false;
                                }else if (isNaN($('input[name=txtPositionX]').val())) {
                                    $('.msg-positionX').text('Enter a valid latitude.');
                                    $('#txtPositionX').addClass("border-red");
                                    valid = false;
                                } else {
                                    $('.msg-positionX').text('');
                                    $('#txtPositionX').removeClass("border-red");
                                }
                                if ($('input[name=txtPositionY]').val() == '') {
                                    $('.msg-positionY').text('Longitude field is required.');
                                    $('#txtPositionY').addClass("border-red");
                                    valid = false;
                                }else if (isNaN($('input[name=txtPositionY]').val())) {
                                    $('.msg-positionY').text('Enter a valid longitude.');
                                    $('#txtPositionY').addClass("border-red");
                                    valid = false;
                                } else {
                                    $('.msg-positionY').text('');
                                    $('#txtPositionY').removeClass("border-red");
                                }
                                if ($('input[name=txtOrder]').val() == '') {
                                    $('.msg-order').text('Order field is required.');
                                    $('#txtOrder').addClass("border-red");
                                    valid = false;
                                } else if (isNaN($('input[name=txtOrder]').val())) {
                                    $('.msg-order').text('Enter a valid order.');
                                    $('#txtOrder').addClass("border-red");
                                    valid = false;
                                } else {
                                    $('.msg-order').text('');
                                    $('#txtOrder').removeClass("border-red");
                                }
                                if (!valid) event.preventDefault();
                                if (valid) {
                                    $('#sbmEmployee').prop('disabled', true);
                                }
                            });
                        })
                    </script>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <ul class="nav nav-pills" role="tablist">
                <?php
                foreach ($formData['arr_language'] as $code => $lang) {
                    $active = $formData['lang_current'] == $code ? "active" : "";
                    ?>
                    <li role="presentation" class="<?php echo $active; ?>">
                        <a href="#<?php echo $code ?>translate"
                           class="tabLanguage"
                           data-lang="<?= $code ?>"
                           aria-controls="<?php echo $code ?>translate"
                           role="tab"
                           data-toggle="tab"><?php echo strtoupper($code)
                                . ' - ' . $lang; ?></a></li>
                <?php } ?>
            </ul>
            <div class="tab-content">
                <?php foreach ($formData['arr_language'] as $code => $lang) {
                    $active = $formData['lang_current'] == $code ? "active" : "";
                    ?>
                    <div role="tabpanel" class="tab-pane <?php echo $active; ?>" id="<?php echo $code; ?>translate">
                        <br>
                        <form name="office-form<?php echo $code; ?>" id="office-form<?php echo $code; ?>" action=""
                              data-parsley-validate class="form-horizontal form-label-left" method="post">
                            <input type="hidden" name="save" id="save" value="<?php echo $code; ?>"/>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Name <span
                                            class="text-danger">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input maxlength="255"
                                           value="<?php echo isset($formData['arr_translate'][$code]["office_name"]) ? $formData['arr_translate'][$code]["office_name"] : "" ?>"
                                           type="text" id="txtName<?php echo $code; ?>" name="txtName"
                                           class="form-control col-md-7 col-xs-12 <?php echo (isset($messages[$code]["office_name"])) ? $messages["status"] : ""; ?>">
                                    <span class="text-danger msg-name-<?php echo $code; ?>"><?php echo isset($messages[$code]["office_name"]) ? $messages[$code]["office_name"] : ""; ?></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="position">Address
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input maxlength="255"
                                           value="<?php echo isset($formData['arr_translate'][$code]["office_address"]) ? $formData['arr_translate'][$code]["office_address"] : "" ?>"
                                           type="text" id="txtAddress<?php echo $code; ?>" name="txtAddress"
                                           class="form-control col-md-7 col-xs-12">

                                </div>
                            </div>
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                    <button name="sbmOffice<?php echo $code; ?>" type="submit" class="btn btn-success">
                                        Save change
                                    </button>
                                </div>
                            </div>
                            <script>
                                $(document).ready(function () {
                                    $('form[name=office-form<?php echo $code; ?>]').submit(function (event) {
                                        valid = true;
                                        if ($('#txtName<?php echo $code; ?>').val() == '') {
                                            valid = false;
                                            $('.msg-name-<?php echo $code;?>').text("Name field is required.");
                                            $('#txtName<?php echo $code; ?>').addClass("border-red");
                                        } else {
                                            $('.msg-name-<?php echo $code;?>').text('');
                                            $('#txtName<?php echo $code; ?>').removeClass("border-red");
                                        }
                                        if (!valid) event.preventDefault();
                                        if (valid) {
                                            $('#sbmOffice<?php echo $code; ?>').prop('disabled', true);
                                        }
                                    });
                                })
                            </script>
                        </form>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
</div>