<div class="page-title">
    <div class="title_left">
        <h3>Delete Cache Tool</h3>
    </div>
</div>
<div class="clearfix"></div>
<?php
if (isset($msg_result['status'])) { ?>
    <div class="alert alert-<?php echo $msg_result['status'] ?> alert-dismissible fade in" role="alert">
        <?php echo $msg_result['msg']; ?>
    </div>
<?php } ?>
<form class="searchForm" name="form-deletecache" method="post" action="">
    <div>
        <div style="border-bottom: 1px solid #c4c4c4;margin-bottom: 20px;padding-bottom: 10px;"></div>
        <div style="border-bottom: 1px solid #c4c4c4;margin-bottom: 20px;padding-bottom: 10px;">
            <h4 style="font-size: 18px">Delete All Cache <br><span class="text-danger" style="font-size: 15px"></span></h4>
            <button type="button" name="btnDeleteAllCache" class="btn btn-success">
                Delete All Cache
            </button>
            <br>
        </div>
        <div style="border-bottom: 1px solid #c4c4c4;margin-bottom: 20px;padding-bottom: 10px;">
            <h4 style="font-size: 18px">Delete Footer Cache <br><span class="text-danger" style="font-size: 15px">(If you change data footer, please click this button)</span></h4>
            <button type="button" name="btnDeleteFooterCache" class="btn btn-success">
                Delete Footer Cache
            </button>
            <br>
        </div>
        <div style="border-bottom: 1px solid #c4c4c4;margin-bottom: 20px;padding-bottom: 10px;">
            <h4 style="font-size: 18px">Delete Register Cache <br><span class="text-danger" style="font-size: 15px">(If you change data register, please click this button)</span></h4>
            <button type="button" name="btnDeleteRegisterCache" class="btn btn-success">
                Delete Register Cache
            </button>
            <br>
        </div>
        <div style="border-bottom: 1px solid #c4c4c4;margin-bottom: 20px;padding-bottom: 10px;">
            <h4 style="font-size: 18px">Delete Promotion Cache <br><span class="text-danger" style="font-size: 15px">(If you change data promotion, please click this button)</span></h4>
            <button type="button" name="btnDeletePromotionCache" class="btn btn-success">
                Delete Promotion Cache
            </button>
            <br>
        </div>
    </div>
</form>
<script>
    $(document).ready(function () {
        $('button[name=btnDeleteAllCache]').click(function () {
            $('form[name=form-deletecache]').prop('action', '<?php echo $this->url->get('/delete-all-cache'); ?>');
            $('form[name=form-deletecache]').submit();
        });
        $('button[name=btnDeleteFooterCache]').click(function () {
            $('form[name=form-deletecache]').prop('action', '<?php echo $this->url->get('/delete-footer-cache'); ?>');
            $('form[name=form-deletecache]').submit();
        });
        $('button[name=btnDeleteRegisterCache]').click(function () {
            $('form[name=form-deletecache]').prop('action', '<?php echo $this->url->get('/delete-register-cache'); ?>');
            $('form[name=form-deletecache]').submit();
        });
        $('button[name=btnDeletePromotionCache]').click(function () {
            $('form[name=form-deletecache]').prop('action', '<?php echo $this->url->get('/delete-promotion-cache'); ?>');
            $('form[name=form-deletecache]').submit();
        });
    });
</script>