<?php
$urlPage = "?";
if(strlen($this->dispatcher->getParam("txtSearch"))> 0){
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtSearch" => $this->dispatcher->getParam("txtSearch")));
}
if(strlen($this->dispatcher->getParam("slStatus")) > 0) {
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("slStatus" => $this->dispatcher->getParam("slStatus")));
}
if(strlen($this->dispatcher->getParam("txtFrom")) > 0) {
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtFrom" => $this->dispatcher->getParam("txtFrom")));
}
if(strlen($this->dispatcher->getParam("txtTo")) > 0) {
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtTo" => $this->dispatcher->getParam("txtTo")));
}
?>
<div class="page-title">
    <div class="title_left">
        <h3>Translate History</h3>
    </div>
</div>
<div class="clearfix"></div>
<form class="searchForm" name="searchForm" method="post">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <div class="row ">
                        <div class="col-md-1">
                            <h2>Keyword</h2>
                        </div>
                        <div class="col-md-2">
                            <input class="form-control" type="text" name="txtSearch" maxlength="255" placeholder="ID, Table" value="<?php echo isset($keyword) ? $keyword : ""; ?>">
                        </div>
                        <div class="col-md-1">
                            <select class="form-control" name="slStatus" id="slStatus">
                                <option value="">All Status</option>
                                <option value="Success"<?php echo $slStatus=='Success' ? ' selected' : '' ?>>Success</option>
                                <option value="Fail"<?php echo $slStatus=='Fail' ? ' selected' : '' ?>>Fail</option>
                            </select>
                        </div>
                        <div class="col-md-1">
                            <h2>From date</h2>
                        </div>
                        <div class="col-md-2">
                            <input name="txtFrom" id="txtFrom" autocomplete="off" type="text" class="form-control datepicker-here" data-timepicker="true" data-time-format='hh:ii' placeholder="From Date" value="<?php echo isset($from) ? $from : ''; ?>" >
                        </div>
                        <div class="col-md-1">
                            <h2>To date</h2>
                        </div>
                        <div class="col-md-2">
                            <input name="txtTo" id="txtTo" autocomplete="off" type="text" class="form-control datepicker-here" data-timepicker="true" data-time-format='hh:ii' placeholder="To Date" value="<?php echo isset($to) ? $to : ''; ?>" >
                        </div>
                        <div class="col-md-1">
                            <button type="button" name="search" class="btn btn-success">Search</button>
                        </div>
                    </div>
                    <div>
                        <strong>Total</strong>
                        <?php echo $page->total_items ?> records <br>
                        <strong>Total character: </strong>
                        <?= $totalCharacter?>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered">
                            <thead class="table_header">
                            <tr class="headings">
                                <th width="50px" class="column-title">ID</th>
                                <th class="column-title">Table</th>
                                <th class="column-title">Record Id</th>
                                <th width="160px" class="column-title">Source Lang Code</th>
                                <th width="160px" class="column-title">Target Lang Code</th>
                                <th width="160px" class="column-title">Format</th>
                                <th width="160px" class="column-title">Status</th>
                                <th width="160px" class="column-title">Reason</th>
                                <th width="160px" class="column-title">Time</th>
                                <th class="column-title">Count character</th>
                                <th width="70px"></th>
                            </tr>
                            </thead>
                            <tbody class="tb_body">
                            <?php foreach ($page->items as $item ) {
                                /**
                                 * @var \Forexceccom\Models\ForexcecTranslateHistory $item
                                 */
                                ?>
                                <tr>
                                    <td class="text-center"><?php echo $item->getHistoryId(); ?></td>
                                    <td class="text-center"><?php echo $item->getHistoryTable(); ?></td>
                                    <td class="text-center"><?php echo $item->getHistoryRecordId() ?></td>
                                    <td class="text-center"><?php echo $item->getHistorySourceLangCode(); ?></td>
                                    <td class="text-center"><?php echo $item->getHistoryTargetLangCode(); ?></td>
                                    <td class="text-center"><?php echo $item->getHistoryFormat(); ?></td>
                                    <td class="text-center"><?php echo $item->getHistoryStatus(); ?></td>
                                    <td>
                                        <?php $reason = (array)json_decode($item->getHistoryMessage());
                                        foreach ($reason as $key => $item_reason){
                                            if(is_array($item_reason) || is_object($item_reason)){
                                                echo '<strong><u>'.$key.':</u></strong><br>';
                                                $item_reason_arr = (array)$item_reason;
                                                echo '<pre>';
                                                print_r($item_reason_arr);
                                            }else{
                                                echo '<strong><u>'.$key.': </u></strong>'.$item_reason.'<br>';
                                            }
                                        }
                                        ?>
                                    </td>
                                    <td class=" "><?php echo $this->my->formatDateTime($item->getHistoryInsertTime(),false) ?></td>
                                    <td class="text-center"><?php echo $item->getHistoryStatus() == \Forexceccom\Models\ForexcecTranslateHistory::STATUS_SUCCESS ? mb_strlen($item->getHistoryDataSource()) : 0; ?></td>
                                    <td class="text-center"><a class="btn btn-primary btn-xs margin-0" style="" href="<?php echo $this->url->get("view-translate-history?id=".$item->getHistoryId()); ?>">View</a></td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="clearfix"></div>
                    <div class="row">
                        <div class="col-md-6 pull-right">
                            <?php if($page->total_pages > 1) {?>
                                <nav class="paginate-footer">
                                    <?php  if($urlPage != "?") $urlPage .= "&";
                                    $urlPage .= "page=";
                                    echo $this->my->renderPagination($urlPage, $page->current, $page->total_pages, 2);
                                    ?>
                                </nav>
                            <?php }?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <button type="submit" name="btnExportcsv" class="btn btn-warning alignright">Export to CSV</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script>
    $(document).ready(function(){
        $('button[name=search]').click(function() {
            $('form[name=searchForm]').prop('action','<?php echo $this->url->get('/list-translate-history'); ?>');
            $('form[name=searchForm]').submit();
        });
    });
</script>

