
<div class="page-title">
    <div class="title_left">
        <h3 class="type-title">Translate History Detail ID = <?php echo $record_model->getHistoryId(); ?></h3>
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_content">
                <br />
                <table class="table table-hover table-striped table-responsive table-bordered table-activity">
                    <tbody>
                    <tr>
                        <td>Site</td>
                        <td><?php echo $record_model->getHistorySite(); ?></td>
                    </tr>
                    <tr>
                        <td>Table</td>
                        <td><?php echo $record_model->getHistoryTable(); ?></td>
                    </tr>
                    <tr>
                        <td>Record Id</td>
                        <td><?php echo $record_model->getHistoryRecordId(); ?></td>
                    </tr>
                    <tr>
                        <td>Source lang code</td>
                        <td><?php echo $record_model->getHistorySourceLangCode(); ?></td>
                    </tr>
                    <tr>
                        <td>Target lang code</td>
                        <td><?php echo $record_model->getHistoryTargetLangCode(); ?></td>
                    </tr>
                    <tr>
                        <td>Format</td>
                        <td><?php echo $record_model->getHistoryFormat(); ?></td>
                    </tr>
                    <tr>
                        <td>Status</td>
                        <td><?php echo $record_model->getHistoryStatus(); ?></td>
                    </tr>
                    <tr>
                        <td>Reason</td>
                        <td>
                            <?php $reason = (array)json_decode($record_model->getHistoryMessage());
                            foreach ($reason as $key => $item_reason){
                                if(is_array($item_reason) || is_object($item_reason)){
                                    echo '<strong><u>'.$key.':</u></strong><br>';
                                    $item_reason_arr = (array)$item_reason;
                                    echo '<pre>';
                                    print_r($item_reason_arr);
                                }else{
                                    echo '<strong><u>'.$key.': </u></strong>'.$item_reason.'<br>';
                                }
                            }
                            ?>
                        </td>
                    </tr>

                    <tr>
                        <td>Insert Time</td>
                        <td><?php echo $this->my->formatDateTime($record_model->getHistoryInsertTime(),false); ?></td>
                    </tr>
                    <tr>
                        <td>Count Characters</td>
                        <td><?php echo $record_model->getHistoryStatus() == \Forexceccom\Models\ForexcecTranslateHistory::STATUS_SUCCESS ? mb_strlen($record_model->getHistoryDataSource()) : 0; ?></td>
                    </tr>
                    <tr>
                        <td>Content Input</td>
                        <td> <textarea style="width: 100%"  ><?php echo $record_model->getHistoryDataSource(); ?></textarea></td>
                    </tr>
                    </tbody>
                </table>
                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-1">
                    <a class="btn btn-primary" href="<?php echo $this->url->get("/list-translate-history"); ?>">Back List</a>
                </div>
            </div>
        </div>
    </div>
</div>

