<script>
    $( document ).ready(function() {
        var id = <?php echo $oldinput["glossary_id"]; ?>;
        $('#txtName').on('input', function() {
            var str = $(this).val();
            if(id == -1) {
                var str_slug = slugify(str);
                $('#txtKeyword').val(str_slug);
                $('#txtTitle').val(str);
                $('#txtMetaKey').val(str);
                $('#txtMetaDesc').val(str);
            }
        });
        $('form[name=glossary-form]').submit(function(event) {
            var valid = true;
            if($('input[name=txtName]').val() == '') {
                $('.msg-name').text('Name field is required.');
                $('#txtName').addClass("border-red");
                valid = false;
            } else {
                $('.msg-name').text('');
                $('#txtName').removeClass("border-red");
            }
            if($('input[name=txtTitle]').val() == '') {
                $('.msg-title').text('Title field is required.');
                $('#txtTitle').addClass("border-red");
                valid = false;
            } else {
                $('.msg-title').text('');
                $('#txtTitle').removeClass("border-red");
            }
            if($('input[name=txtKeyword]').val() == '') {
                $('.msg-keyword').text('Keyword field is required.');
                $('#txtKeyword').addClass("border-red");
                valid = false;
            } else {
                $('.msg-keyword').text('');
                $('#txtKeyword').removeClass("border-red");
            }
            if($('textarea[name=txtMetaKey]').val() == '') {
                $('.msg-metakeyword').text('Meta keyword field is required.');
                $('#txtMetaKey').addClass("border-red");
                valid = false;
            } else {
                $('.msg-metakeyword').text('');
                $('#txtMetaKey').removeClass("border-red");
            }
            if($('textarea[name=txtMetaDesc]').val() == '') {
                $('.msg-metadescription').text('Meta description field is required.');
                $('#txtMetaDesc').addClass("border-red");
                valid = false;
            } else {
                $('.msg-metadescription').text('');
                $('#txtMetaDesc').removeClass("border-red");
            }
            if($('input[name=txtOrder]').val() == '') {
                $('.msg-order').text('Order field is required.');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else if (isNaN($('input[name=txtOrder]').val())) {
                $('.msg-order').text('Enter a valid order.');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else {
                $('.msg-order').text('');
                $('#txtOrder').removeClass("border-red");
            }

            if( ! valid ) event.preventDefault();
            if( valid ) {
                $('button[name=sbmGlossary]').prop('disabled', true);
            }
        });
    });
</script>
<?php $border_error = 'border-red' ?>
<div class="page-title">
    <div class="title_left">
        <h3 class="glossary-title">Glossary</h3>
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">Form Create
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br />
                <form name="glossary-form" id="glossary-form" data-parsley-validate class="form-horizontal form-label-left" method="post">
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Name <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($oldinput["glossary_name"]) ? $oldinput["glossary_name"] : "" ?>" type="text" id="txtName" name="txtName"   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["name"])) ? $border_error : ""; ?>">
                            <span class="text-danger msg-name"><?php echo isset($messages["name"]) ? $messages["name"] : ""; ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Title <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($oldinput["glossary_title"]) ? $oldinput["glossary_title"] : "" ?>" type="text" id="txtTitle" name="txtTitle"   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["title"])  ) ? $border_error : ""; ?>">
                            <span class="text-danger msg-title"><?php echo isset($messages["title"]) ? $messages["title"] : "";?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Keyword <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($oldinput["glossary_keyword"]) ? $oldinput["glossary_keyword"] : "" ?>" type="text" id="txtKeyword" name="txtKeyword"   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["keyword"])) ? $border_error : ""; ?>">
                            <span class="text-danger msg-keyword"><?php echo isset($messages["keyword"]) ? $messages["keyword"] : "";?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Meta keyword <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea style="height: 100px" id="txtMetaKey" class="form-control <?php echo (isset($messages["meta_keyword"])) ? $border_error : ""; ?>" name ="txtMetaKey"  ><?php echo isset($oldinput["glossary_meta_keyword"]) ? $oldinput["glossary_meta_keyword"] : "" ?></textarea>
                            <span class="text-danger msg-metakeyword"><?php echo isset($messages["meta_keyword"]) ? $messages["meta_keyword"] : "";?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Meta description <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea style="height: 100px" id="txtMetaDesc" class="form-control <?php echo (isset($messages["meta_description"])) ? $border_error : ""; ?>" name ="txtMetaDesc"  ><?php echo isset($oldinput["glossary_meta_description"]) ? $oldinput["glossary_meta_description"] : "" ?></textarea>
                            <span class="text-danger msg-metadescription"><?php echo isset($messages["meta_description"]) ? $messages["meta_description"] : "";?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Icon</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($oldinput["glossary_icon"]) ? $oldinput["glossary_icon"] : "" ?>" id="txtIcon" name="txtIcon" class="form-control col-md-7 col-xs-12 " type="text" >
                         </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Meta image</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($oldinput["glossary_meta_image"]) ? $oldinput["glossary_meta_image"] : "" ?>" type="text" id="txtMetaImage" name="txtMetaImage" class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Order <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="10" value="<?php echo isset($oldinput["glossary_order"]) ? $oldinput["glossary_order"] : "" ?>" type="text" id="txtOrder" name="txtOrder"  class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["order"])) ? $border_error : ""; ?>">
                            <span class="text-danger msg-order"><?php echo isset($messages["order"]) ? $messages["order"] : "";?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Is Home </label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radIsHome" value="Y" <?php echo (isset($oldinput["glossary_ishome"]) && $oldinput["glossary_ishome"]=="Y" )  ? "checked" : '' ; ?>>Yes<span class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radIsHome" value="N" <?php echo (isset($oldinput["glossary_ishome"]) && $oldinput["glossary_ishome"]=="N" )  ? "checked" : '' ; ?>>No<span class="checkmark"></span></label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Active </label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radActive" value="Y" <?php echo (isset($oldinput["glossary_active"]) && $oldinput["glossary_active"]=="Y" )  ? "checked" : '' ; ?>>Yes<span class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radActive" value="N" <?php echo (isset($oldinput["glossary_active"]) && $oldinput["glossary_active"]=="N" )  ? "checked" : '' ; ?>>No<span class="checkmark"></span></label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtSummary">Summary </label>
                        <div class="col-md-6 col-sm-6 col-xs-12 control-bg">
                            <textarea class="form-control" id="txtSummary" name ="txtSummary" style="width: 750px;height: 212px;" ><?php echo isset($oldinput["glossary_summary"]) ? $oldinput["glossary_summary"] : ""; ?></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Content
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea  id="txtContent" class="form-control" name ="txtContent"  ><?php echo isset($oldinput["glossary_content"]) ? $oldinput["glossary_content"] : "" ?></textarea>
                        </div>
                    </div>
                    <script type="text/javascript">
                        window.onload = function()
                        {
                            var oFCKeditor2 = new FCKeditor('txtContent') ;
                            oFCKeditor2.Height = '400';
                            oFCKeditor2.Width = '700';
                            oFCKeditor2.ToolbarSet = "Default" ;
                            oFCKeditor2.Basepath = '../backend/fckeditor/';
                            oFCKeditor2.ReplaceTextarea() ;
                        }
                    </script>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button name="sbmGlossary" type="submit" class="btn btn-success">Save change</button>
                            <a class="btn btn-primary" href="list-glossary">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>