<script>
    $(document).ready(function () {
        $('form[name=glossary-form]').submit(function (event) {
            var valid = true;
            if ($('input[name=txtKeyword]').val() == '') {
                $('.msg-keyword').text('Keyword field is required.');
                $('#txtKeyword').addClass("border-red");
                valid = false;
            } else {
                $('.msg-keyword').text('');
                $('#txtKeyword').removeClass("border-red");
            }
            if ($('input[name=txtOrder]').val() == '') {
                $('.msg-order').text('Order field is required.');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else if (isNaN($('input[name=txtOrder]').val())) {
                $('.msg-order').text('Enter a valid order.');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else {
                $('.msg-order').text('');
                $('#txtOrder').removeClass("border-red");
            }

            if (!valid) event.preventDefault();
            if (valid) {
                $('button[name=sbmGlossary]').prop('disabled', true);
            }
        });

        /*oFCKeditor2*/
        var oFCKeditor2;
        oFCKeditor2 = new FCKeditor('txtContent' + '<?= $formData['lang_current'] ?>');
        oFCKeditor2.Height = '400';
        oFCKeditor2.Width = '700';
        oFCKeditor2.ToolbarSet = "Default";
        oFCKeditor2.Basepath = '../backend/fckeditor/';
        oFCKeditor2.ReplaceTextarea();
        var list_lang = ["<?= $formData['lang_current'] ?>"];
        $('.tabLanguage').click(function (e) {
            var lang = $(this).data('lang');
            if (list_lang.indexOf(lang) == -1) {
                oFCKeditor2 = new FCKeditor('txtContent' + lang);
                oFCKeditor2.Height = '400';
                oFCKeditor2.Width = '700';
                oFCKeditor2.ToolbarSet = "Default";
                oFCKeditor2.Basepath = '../backend/fckeditor/';
                oFCKeditor2.ReplaceTextarea();
            }
            list_lang.push(lang);
        });

        /*END oFCKeditor2*/
    });
</script>
<?php $border = 'border-red'; ?>
<div class="page-title">
    <div class="title_left">
        <h3 class="glossary-title">Glossary</h3>
    </div>
</div>
<?php if (!empty($messages['message'])) {
    ?>
    <div class="clearfix"></div>
    <p style="font-size:18px;text-align:center" class="alert alert-<?php echo $messages['typeMessage'] ?>">
        <?php echo $messages['message']; ?>
    </p>
<?php } ?>


<div class="clearfix"></div>
<p id="alertInsertTranslate" hidden style="font-size:18px;text-align:center" class="alert alert-success">
    Update & Translate Glossary success
</p>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">Form Edit
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br/>
                <form name="glossary-form" id="glossary-form" data-parsley-validate
                      class="form-horizontal form-label-left" method="post">
                    <input type="hidden" name="save" id="save"
                           value="<?php echo \Forexceccom\Models\ForexcecLanguage::GENERAL; ?>"/>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Keyword <span
                                class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255"
                                   value="<?php echo isset($formData["glossary_keyword"]) ? $formData["glossary_keyword"] : "" ?>"
                                   type="text" id="txtKeyword" name="txtKeyword"
                                   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["keyword"])) ? $border : ""; ?>">
                            <span class="text-danger msg-keyword"><?php echo isset($messages["keyword"]) ? $messages["keyword"] : ""; ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Icon</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255"
                                   value="<?php echo isset($formData["glossary_icon"]) ? $formData["glossary_icon"] : "" ?>"
                                   type="text" id="txtIcon" name="txtIcon"
                                   class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Meta image</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255"
                                   value="<?php echo isset($formData["glossary_meta_image"]) ? $formData["glossary_meta_image"] : "" ?>"
                                   type="text" id="txtMetaImage" name="txtMetaImage"
                                   class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Order <span
                                class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="10"
                                   value="<?php echo isset($formData["glossary_order"]) ? $formData["glossary_order"] : "" ?>"
                                   type="text" id="txtOrder" name="txtOrder"
                                   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["order"])) ? $border : ""; ?>">
                            <span class="text-danger msg-order"><?php echo isset($messages["order"]) ? $messages["order"] : ""; ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Is Home </label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radIsHome"
                                                                  value="Y" <?php echo (isset($formData["glossary_ishome"]) && $formData["glossary_ishome"] == "Y") ? "checked" : ''; ?>>Yes<span
                                        class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radIsHome"
                                                                  value="N" <?php echo (isset($formData["glossary_ishome"]) && $formData["glossary_ishome"] == "N") ? "checked" : ''; ?>>No<span
                                        class="checkmark"></span></label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Active </label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radActive"
                                                                  value="Y" <?php echo (isset($formData["glossary_active"]) && $formData["glossary_active"] == "Y") ? "checked" : ''; ?>>Yes<span
                                    class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radActive"
                                                                  value="N" <?php echo (isset($formData["glossary_active"]) && $formData["glossary_active"] == "N") ? "checked" : ''; ?>>No<span
                                    class="checkmark"></span></label>
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button name="sbmGlossary" type="submit" class="btn btn-success">Save change</button>
                            <a class="btn btn-primary"
                               href="<?php echo $this->url->get("/list-glossary?slcLang=" . $formData['lang_current']); ?>">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <ul class="nav nav-pills" role="tablist">
                <?php
                foreach ($formData['arr_language'] as $code => $lang) {
                    $active = $formData['lang_current'] == $code ? "active" : "";
                    ?>
                    <li role="presentation" class="<?php echo $active; ?>">
                        <a href="#<?php echo $code ?>translate"
                           class="tabLanguage"
                           data-lang="<?= $code ?>"
                           aria-controls="<?php echo $code ?>translate"
                           role="tab"
                           data-toggle="tab"><?php echo strtoupper($code)
                                . ' - ' . $lang; ?></a></li>
                <?php } ?>
            </ul>
            <div class="tab-content">
                <?php foreach ($formData['arr_language'] as $code => $lang) {
                    $active = $formData['lang_current'] == $code ? "active" : "";
                    ?>
                    <div role="tabpanel" class="tab-pane <?php echo $active; ?>" id="<?php echo $code; ?>translate">
                        <br>
                        <form name="glossary-form<?php echo $code; ?>" id="glossary-form<?php echo $code; ?>" action=""
                              data-parsley-validate class="form-horizontal form-label-left" method="post">
                            <input type="hidden" name="save" id="save" value="<?php echo $code; ?>"/>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Name <span
                                        class="text-danger">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input maxlength="255"
                                           value="<?php echo isset($formData['arr_translate'][$code]["glossary_name"]) ? $formData['arr_translate'][$code]["glossary_name"] : "" ?>"
                                           type="text" id="txtName<?php echo $code; ?>" name="txtName"
                                           class="form-control col-md-7 col-xs-12 <?php echo (isset($messages[$code]["name"])) ? $border : ""; ?>">
                                    <span class="text-danger msg-name-<?php echo $code; ?>"><?php echo isset($messages[$code]["name"]) ? $messages[$code]["name"] : ""; ?></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Title <span
                                        class="text-danger">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input maxlength="255"
                                           value="<?php echo isset($formData['arr_translate'][$code]["glossary_title"]) ? $formData['arr_translate'][$code]["glossary_title"] : "" ?>"
                                           type="text" id="txtTitle<?php echo $code; ?>" name="txtTitle"
                                           class="form-control col-md-7 col-xs-12 <?php echo (isset($messages[$code]["title"])) ? $border : ""; ?>">
                                    <span class="text-danger msg-title-<?php echo $code; ?>"><?php echo isset($messages[$code]["title"]) ? $messages[$code]["title"] : ""; ?></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Meta keyword
                                    <span class="text-danger">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <textarea style="height: 100px;" id="txtMetaKey<?php echo $code; ?>"
                                              class="form-control <?php echo (isset($messages[$code]["meta_keyword"])) ? $border : ""; ?>"
                                              name="txtMetaKey"><?php echo isset($formData['arr_translate'][$code]["glossary_meta_keyword"]) ? $formData['arr_translate'][$code]["glossary_meta_keyword"] : "" ?></textarea>
                                    <span class="text-danger msg-metakeyword-<?php echo $code; ?>"><?php echo isset($messages[$code]["meta_keyword"]) ? $messages[$code]["meta_keyword"] : ""; ?></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Meta
                                    description <span class="text-danger">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <textarea style="height: 100px;" id="txtMetaDesc<?php echo $code; ?>"
                                              class="form-control <?php echo (isset($messages[$code]["meta_description"])) ? $border : ""; ?>"
                                              name="txtMetaDesc"><?php echo isset($formData['arr_translate'][$code]["glossary_meta_description"]) ? $formData['arr_translate'][$code]["glossary_meta_description"] : "" ?></textarea>
                                    <span class="text-danger msg-metadescription-<?php echo $code; ?>"><?php echo isset($messages[$code]["meta_description"]) ? $messages[$code]["meta_description"] : ""; ?></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12"
                                       for="txtSummary">Summary </label>
                                <div class="col-md-6 col-sm-6 col-xs-12 control-bg">
                                        <textarea class="form-control" id="txtSummary<?php echo $code; ?>" name="txtSummary"
                                                  style="width:699px;height: 212px;"><?php echo isset($formData['arr_translate'][$code]["glossary_summary"]) ? $formData['arr_translate'][$code]["glossary_summary"] : ""; ?></textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Content
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <textarea id="txtContent<?php echo $code; ?>" class="form-control" style="width:699px;height: 212px;"
                                              name="txtContent"><?php echo isset($formData['arr_translate'][$code]["glossary_content"]) ? $formData['arr_translate'][$code]["glossary_content"] : "" ?></textarea>
                                </div>
                            </div>
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                    <button name="sbmGlossary<?php echo $code; ?>" type="submit"
                                            class="btn btn-success">
                                        <?php echo 'Save ' . $lang; ?>
                                    </button>
                                </div>
                            </div>
                            <script>
                                $(document).ready(function () {
                                    $('#txtName<?php echo $code; ?>').on('input', function () {
                                        var id = <?php echo isset($formData['arr_translate'][$code]["glossary_id"]) ? $formData['arr_translate'][$code]["glossary_id"] : -1;?>;
                                        if (id < 0) {
                                            var str = $(this).val();
                                            $('#txtTitle<?php echo $code; ?>').val(str);
                                            $('#txtMetaKey<?php echo $code; ?>').val(str);
                                            $('#txtMetaDesc<?php echo $code; ?>').val(str);
                                        }
                                    });
                                    $('form[name=glossary-form<?php echo $code; ?>]').submit(function (event) {
                                        valid = true;
                                        if ($('#txtName<?php echo $code; ?>').val() == '') {
                                            valid = false;
                                            $('.msg-name-<?php echo $code;?>').text("Name field is required.");
                                            $('#txtName<?php echo $code; ?>').addClass("border-red");
                                        } else {
                                            $('.msg-name-<?php echo $code;?>').text('');
                                            $('#txtName<?php echo $code; ?>').removeClass("border-red");
                                        }
                                        if ($('#txtTitle<?php echo $code; ?>').val() == '') {
                                            $('.msg-title-<?php echo $code; ?>').text('Title field is required.');
                                            $('#txtTitle<?php echo $code; ?>').addClass("border-red");
                                            valid = false;
                                        } else {
                                            $('.msg-title-<?php echo $code; ?>').text('');
                                            $('#txtTitle<?php echo $code; ?>').removeClass("border-red");
                                        }
                                        if ($('#txtMetaKey<?php echo $code; ?>').val() == '') {
                                            $('.msg-metakeyword-<?php echo $code; ?>').text('Meta keyword field is required.');
                                            $('#txtMetaKey<?php echo $code; ?>').addClass("border-red");
                                            valid = false;
                                        } else {
                                            $('.msg-metakeyword-<?php echo $code; ?>').text('');
                                            $('#txtMetaKey<?php echo $code; ?>').removeClass("border-red");
                                        }
                                        if ($('#txtMetaDesc<?php echo $code; ?>').val() == '') {
                                            $('.msg-metadescription-<?php echo $code; ?>').text('Meta description field is required.');
                                            $('#txtMetaDesc<?php echo $code; ?>').addClass("border-red");
                                            valid = false;
                                        } else {
                                            $('.msg-metadescription-<?php echo $code; ?>').text('');
                                            $('#txtMetaDesc<?php echo $code; ?>').removeClass("border-red");
                                        }
                                        if (!valid) event.preventDefault();
                                        if (valid) {
                                            $('#sbmGlossary<?php echo $code; ?>').prop('disabled', true);
                                        }
                                    });
                                });
                            </script>
                        </form>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
</div>