<?php
$urlPage = "?";
if (strlen($this->dispatcher->getParam("txtSearch")) > 0) {
    if ($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtSearch" => $this->dispatcher->getParam("txtSearch")));
}
$slcLang = $this->dispatcher->getParam("slcLang");
if ($this->dispatcher->getParam("slcLang") != "") {
    if ($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("slcLang" => $slcLang));
}
$radMatch = $this->dispatcher->getParam("radMatch");
if ($urlPage != "?") $urlPage .= "&";
$urlPage .= http_build_query(array("radMatch" => $radMatch));
?>

<div class="page-title">
    <div class="title_left">
        <h3>Glossary</h3>
    </div>
</div>
<?php if (isset($msg_result['status'])) { ?>
    <div class="clearfix"></div>
    <div class="alert alert-<?php echo $msg_result['status'] ?> alert-dismissible fade in" role="alert">
        <?php echo $msg_result['msg']; ?>
    </div>
<?php } ?>
<?php if (isset($msg_delete['success']) && !empty($msg_delete['success'])) { ?>
    <div class="clearfix"></div>
    <div class="alert alert-success alert-dismissible fade in" role="alert">
        <?php echo $msg_delete['success']; ?>
    </div>
<?php } ?>
<div class="clearfix"></div>
<div id="loading" hidden>
    <img class="lazyload padding-top10" src="<?php echo $this->url->getStatic('backend/'); ?>img/waiting.gif"
         style="vertical-align:middle;position: relative;z-index: 10001;"/> Processing...
</div>
<form class="searchForm" name="form-glossary" method="post" action="">
    <?php
    $keyword = $this->dispatcher->getParam("txtSearch");
    $replace = $this->dispatcher->getParam("txtReplace");
    ?>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <div class="row ">
                        <div class="col-md-1">
                            <h2 class="">Find</h2>
                        </div>
                        <div class="col-md-4">
                            <textarea class="form-control" type="text" name="txtSearch"
                                      placeholder="ID, Name, Title, Meta Keyword, Meta Description, Summary, Content"><?php echo isset($keyword) ? $keyword : ''; ?></textarea>
                        </div>
                        <div class="col-md-1">
                            <h2 class="">Replace</h2>
                        </div>
                        <div class="col-md-4">
                            <textarea class="form-control" type="text" name="txtReplace"
                                      placeholder="Name, Title, Meta Keyword, Meta Description, Summary, Content"><?php echo isset($replace) ? $replace : ''; ?></textarea>
                        </div>
                    </div>
                    <div class="row" style="margin-top:15px ">
                        <h2 class="col-md-1">Language</h2>
                        <div class="col-md-2">
                            <select class="form-control" name="slcLang" id="slcLang">
                                <?php
                                echo isset($select_lang) ? $select_lang : "";
                                ?>
                            </select>
                        </div>
                        <div class="col-md-6 " style="display: flex">
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="radMatch" id="radMatch"
                                       value="match" <?php echo ($radMatch == 'match') ? 'checked' : ''; ?>>
                                <label class="form-check-label" for="radMatch">
                                    Match
                                </label>
                            </div>
                            <div class="form-check" style="margin-left: 10px;margin-right: 10px">
                                <input class="form-check-input" type="radio" name="radMatch" id="notMatch"
                                       value="notmatch" <?php echo ($radMatch == 'notmatch') ? 'checked' : ''; ?>>
                                <label class="form-check-label" for="notMatch">
                                    Not match
                                </label>
                            </div>
                            <button type="button" name="search" class="btn btn-success ">Search</button>
                            <button style="margin-right:20px;margin-left:20px" type="submit" name="btnReplace" class="btn btn-danger" id="btnReplace" onclick="return confirm('Are you sure you want to Replace?');">Replace
                            </button>
                            <a class="btn btn-info"
                               href="<?php echo $this->url->get("/create-glossary"); ?>">Add
                                New</a>
                        </div>
                    </div>
                    <div>
                        <strong>Total</strong>
                        <?php echo $list_glossary->total_items ?> records
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered">
                            <thead class="table_header">
                            <tr class="headings">
                                <th style="text-align: left" width="50px"><label class="container_checkbox"><input
                                                type="checkbox" id="checkboxAll"><span
                                                class="checkmark_checkbox"></span></label></th>
                                <th width="50px" class="column-title">ID</th>
                                <th width="" class="column-title">Name</th>
                                <th width="" class="column-title">Language</th>
                                <th width="50px" class="column-title">Order</th>
                                <th width="50px" class="column-title">Active</th>
                                <th width="80px" class="column-title no-link last"><span class="nobr">Action</span></th>
                            </tr>
                            </thead>
                            <tbody class="tb_body">
                            <?php foreach ($list_glossary->items as $item) { ?>
                                <tr>
                                    <td><label class="container_checkbox"><input class="check" name="item[]"
                                                                                 value="<?php echo $item->getGlossaryId() ?>"
                                                                                 type="checkbox"><span
                                                    class="checkmark_checkbox"></span></label></td>
                                    <td class=" "><?php echo $item->getGlossaryId() ?></td>
                                    <td class=" "><?php echo $item->getGlossaryName() ?></td>
                                    <td class=" "><?php echo \Forexceccom\Repositories\Language::getNameByCode($slcLang); ?></td>
                                    <td class=" "><?php echo $item->getGlossaryOrder() ?></td>
                                    <td class="text-center" data-title="Active">
                                        <?php
                                        $status = $item->getGlossaryActive();
                                        $classStatus = ($status == "Y") ? "success" : "danger";
                                        ?>
                                        <span class="label label-<?php echo $classStatus; ?>"><?php echo $status; ?></span>
                                    </td>
                                    <td><a class="btn btn-primary btn-xs margin-0"
                                           href="<?php echo $this->url->get("/edit-glossary?id=" . $item->getGlossaryId()); ?> ">View</a>
                                    </td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="clearfix"></div>
                    <div class="row">
                        <div class="col-md-6 ">
                            <label for="slcAction">With Selected:</label>
                            <select class="form-control" id="slcAction" name="slcAction"
                                    style="display: inline-block;width: 40%">
                                <option value="" selected>Please select</option>
                                <option value="drop">Drop</option>
                            </select>
                        </div>
                        <div class="col-md-6">
                            <?php if ($list_glossary->total_pages > 1) { ?>
                                <nav class="paginate-footer">
                                    <?php if ($urlPage != "?") $urlPage .= "&";
                                    $urlPage .= "page=";
                                    echo $this->my->renderPagination($urlPage, $list_glossary->current, $list_glossary->total_pages, 2);
                                    ?>
                                </nav>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script>
    $(document).ready(function () {
        $('button[name=search]').click(function () {
            $('form[name=form-glossary]').prop('action', '<?php echo $this->url->get('/list-glossary'); ?>');
            $('form[name=form-glossary]').submit();
        });

        $('.delete-all').click(function () {
            $('form[name=form-glossary]').prop('action', '<?php echo $this->url->get('/delete-glossary'); ?>');
            $('form[name=form-glossary]').submit();
        });

    });
</script>