<?php

$urlPage = "?";

$keyword = $this->dispatcher->getParam("txtSearch");
$update_from = $this->dispatcher->getParam("txtUpdateFrom");
$update_to = $this->dispatcher->getParam("txtUpdateTo");

if (strlen($this->dispatcher->getParam("txtSearch")) > 0) {
    if ($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtSearch" => $this->dispatcher->getParam("txtSearch")));
}
if (strlen($this->dispatcher->getParam("txtUpdateFrom")) > 0) {
    if ($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtUpdateFrom" => $this->dispatcher->getParam("txtUpdateFrom")));
}
if (strlen($this->dispatcher->getParam("txtUpdateTo")) > 0) {
    if ($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtUpdateTo" => $this->dispatcher->getParam("txtUpdateTo")));
}
if (strlen($this->dispatcher->getParam("slStatus")) > 0) {
    if ($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("slStatus" => $this->dispatcher->getParam("slStatus")));
}
if (strlen($this->dispatcher->getParam("slType")) > 0) {
    if ($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("slType" => $this->dispatcher->getParam("slType")));
}
?>
<div class="page-title">
    <div class="title_left">
        <h3>Sent Email Log</h3>
    </div>
</div>
<div class="clearfix"></div>
<form class="searchForm" name="form-type" method="post">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">

                    <div class="row " style="padding-bottom: 10px">
                        <div class="col-md-1">
                            <h2>Keyword</h2>
                        </div>
                        <div class="col-md-2">
                            <input class="form-control" type="text" name="txtSearch" maxlength="255"
                                   placeholder="ID, Name, Email" value="<?= isset($keyword) ? $keyword : ""; ?>">
                        </div>

                        <div class="col-md-1">
                            <h2>Type</h2>
                        </div>
                        <div class="col-md-2">
                            <select class="form-control" name="slType" id="slType">
                                <option value="">All Type</option>
                                <?php echo isset($slType) ? $slType : '' ?>
                            </select>
                        </div>


                        <div class="col-md-1">
                        <h2>Status</h2>
                        </div>
                        <div class="col-md-2">
                            <select class="form-control" name="slStatus" id="slStatus">
                                <option value="">All Status</option>
                                <?php echo isset($slStatus) ? $slStatus : '' ?>
                            </select>
                        </div>


                    </div>
                    <div class="row ">
                        <div class="col-md-1">
                        <h2>From date</h2>
                        </div>
                        <div class="col-md-2">
                            <input name="txtUpdateFrom" id="txtUpdateFrom" autocomplete="off" type="text"
                                   class="form-control datepicker-here" data-timepicker="true" data-time-format='hh:ii'
                                   placeholder="From Date" value="<?= isset($update_from) ? $update_from : ''; ?>">
                        </div>
                        <div class="col-md-1">
                        <h2>To date</h2>
                        </div>
                        <div class="col-md-2">
                            <input name="txtUpdateTo" id="txtUpdateTo" autocomplete="off" type="text"
                                   class="form-control datepicker-here" data-timepicker="true" data-time-format='hh:ii'
                                   placeholder="To Date" value="<?= isset($update_to) ? $update_to : ''; ?>">
                        </div>
                        <div class="col-md-1">
                            <button type="button" name="search" class="btn btn-success">Search</button>
                        </div>
                        <div class="col-md-1 ">
                            <button type="submit" name="btnExportcsv" class="btn btn-warning ">Export to CSV</button>
                        </div>
                    </div>
                    <div>
                        <strong>Total</strong>
                        <?= $page->total_items ?> records
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered">
                            <thead class="table_header">
                            <tr class="headings">
                                <th width="50px" class="column-title">ID</th>
                                <th class="column-title">User Email</th>
                                <th class="column-title">Type</th>
                                <th width="160px" class="column-title">Update Time</th>
                                <th width="160px" class="column-title">Insert Time</th>
                                <th width="50px" class="column-title">Is subscribe</th>
                                <th width="50px" class="column-title">Status </th>
                                <th width="50px" class="column-title no-link last"><span class="nobr">Action </span>
                                </th>
                            </tr>
                            </thead>
                            <tbody class="tb_body">
                            <?php foreach ($page->items as $item) {
                                /**
                                /*@var Forexceccom\Models\ForexcecSentEmailLog $item
                                 */
                                ?>
                                <tr>
                                    <td><?= $item->getSentId(); ?></td>
                                    <td><?= $item->getSentEmail(); ?></td>
                                        <?php $form =  \Forexceccom\Models\ForexcecTemplateAutoEmail::ARRAY_FORM ;
                                        ?>
                                    <td class=" "><?= $form[$item->getSentEmailType()]; ?>
                                    </td>
                                    <td><?= $this->my->formatDateTime($item->getSentUpdateTime(),false);  ?></td>
                                    <td><?= $this->my->formatDateTime($item->getSentInsertTime(),false); ?>
                                    </td>
                                    <td class="text-center" data-title="Active">
                                        <?php
                                        $status = $item->getSentIsSubscribe();
                                        $classStatus = ($status == "Y") ? "success" : "danger";
                                        ?>
                                        <span class="label label-<?php echo $classStatus; ?>"><?php echo $status; ?></span>
                                    </td>
                                    <td class="text-center" data-title="Active">
                                        <?php
                                        $status = $item->getSentStatus();
                                        $classStatus = ($status == "finish") ? "success" : "info";
                                        ?>
                                        <span class="label label-<?php echo $classStatus; ?>"><?php echo $status; ?></span>
                                    </td>
                                    <td class="last">
                                        <a class="btn btn-primary btn-xs margin-0"  href="<?php echo $this->url->get("/view-email-log?id=".$item->getSentId()); ?>">View</a>
                                    </td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="clearfix"></div>
                    <div class="row">
                        <div class="col-md-6 pull-right">
                            <?php if ($page->total_pages > 1) { ?>
                                <nav class="paginate-footer">
                                    <?php if ($urlPage != "?") $urlPage .= "&";
                                    $urlPage .= "page=";
                                    echo $this->my->renderPagination($urlPage, $page->current, $page->total_pages, 2);
                                    ?>
                                </nav>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script>
    $(document).ready(function () {
        $('button[name=search]').click(function () {
            $('form[name=form-type]').prop('action', '<?= $this->url->get('/list-email-log'); ?>');
            $('form[name=form-type]').submit();
        });
    });
</script>

