<?php
/**
 * @var \Forexceccom\Models\ForexcecSentEmailLog $logModel
 */
?>
<div class="page-title">
    <div class="title_left">
        <h3 class="type-title">Sent Email Log: <?= $logModel->getSentEmail() ?> </h3>
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br />
                <h3>Log Information:</h3>

                <table class="table table-hover table-striped table-responsive table-bordered table-activity">
                    <tbody>
                    <tr>
                        <td style="width: 250px" >Email </td>
                        <td><?= $logModel->getSentEmail(); ?></td>
                    </tr>
                    <tr>
                        <td>Type </td>
                        <td><?= \Forexceccom\Models\ForexcecTemplateAutoEmail::ARRAY_FORM[$logModel->getSentEmailType()]; ?></td>
                    </tr>
                    <tr>
                        <td>Status</td>
                        <td><?= $logModel->getSentStatus(); ?></td>
                    </tr>

                    <tr>
                        <td>Subscribe</td>
                        <td>
                            <?php $class_checked = ($logModel->getSentIsSubscribe() == 'Y') ? 'success' : 'danger' ; ?>
                            <span class="badge badge-<?= $class_checked; ?>"><?= $logModel->getSentIsSubscribe(); ?></span>
                        </td>
                    </tr>
                    <tr>
                        <td>Update Time</td>
                        <td><?= $this->my->formatDateTime($logModel->getSentUpdateTime(),false); ?></td>
                    </tr>
                    <tr>
                        <td>Insert Time</td>
                        <td><?= $this->my->formatDateTime($logModel->getSentInsertTime(),false); ?></td>
                    </tr>

                    <?php
                    $arrTemplateEmail = [];
                    $arrEducation = [];
                    $arrTemplateEmailLw = [];
                    $arrEducationLw = [];
                    $log_leadform = $logModel->getSentLogLeadform();
                    $log_lw_user = $logModel->getSentLogLwUser();
                    $sent_log_cron = new \Forexceccom\Repositories\SentEmailLog();
                    $sent_log_cron->viewSentLog($log_leadform,$logModel,$arrTemplateEmail,$arrEducation);
                    $sent_log_cron->viewSentLog($log_lw_user,$logModel,$arrTemplateEmailLw,$arrEducationLw);

                    ?>
                    <?php
                    if (count($arrTemplateEmail) > 0) {
                        ?>
                        <tr>
                            <td>Email Sent Leadform:</td>
                            <td>
                                <?= implode(' <br> ',$arrTemplateEmail) ?>
                            </td>
                        </tr>
                    <?php } ?>

                    <?php
                    if (count($arrEducation) > 0) {
                        ?>
                        <tr>
                            <td>Email Lesson Sent Leadform:</td>
                            <td>
                                <?= implode('; ',$arrEducation) ?>
                            </td>
                        </tr>
                    <?php } ?>
                    <tr>

                        <?php
                        if (count($arrTemplateEmailLw) > 0) {
                        ?>
                        <tr>
                            <td>Email Sent Lw User:</td>
                            <td>
                                <?= implode(' <br> ',$arrTemplateEmailLw) ?>
                            </td>
                        </tr>
                    <?php } ?>

                    <?php
                    if (count($arrEducationLw) > 0) {
                        ?>
                        <tr>
                            <td>Email Lesson Sent Lw User:</td>
                            <td>
                                <?= implode('; ',$arrEducationLw) ?>
                            </td>
                        </tr>
                    <?php } ?>
                </table>
                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-1">
                    <a class="btn btn-primary" href="<?= $this->url->get("/list-email-log"); ?>">Back List</a>
                </div>
            </div>
        </div>
    </div>
</div>

