<?php

$urlPage = "?";

$keyword = $this->dispatcher->getParam("txtSearch");
$from = $this->dispatcher->getParam("txtFrom");
$to = $this->dispatcher->getParam("txtTo");

if (strlen($this->dispatcher->getParam("txtSearch")) > 0) {
    if ($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtSearch" => $this->dispatcher->getParam("txtSearch")));
}
if (strlen($this->dispatcher->getParam("txtFrom")) > 0) {
    if ($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtFrom" => $this->dispatcher->getParam("txtFrom")));
}
if (strlen($this->dispatcher->getParam("txtTo")) > 0) {
    if ($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtTo" => $this->dispatcher->getParam("txtTo")));
}
?>
<div class="page-title">
    <div class="title_left">
        <h3>Lead Form</h3>
    </div>
</div>
<div class="clearfix"></div>
<form class="searchForm" name="form-type" method="post">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <div class="row ">
                        <div class="col-md-1">
                            <h2>Keyword</h2>
                        </div>
                        <div class="col-md-2">
                            <input class="form-control" type="text" name="txtSearch" maxlength="255"
                                   placeholder="ID, Name, Email" value="<?= isset($keyword) ? $keyword : ""; ?>">
                        </div>
                        <h2>From date</h2>
                        <div class="col-md-2">
                            <input name="txtFrom" id="txtFrom" autocomplete="off" type="text"
                                   class="form-control datepicker-here" data-timepicker="true" data-time-format='hh:ii'
                                   placeholder="From Date" value="<?= isset($from) ? $from : ''; ?>">
                        </div>
                        <h2>To date</h2>
                        <div class="col-md-2">
                            <input name="txtTo" id="txtTo" autocomplete="off" type="text"
                                   class="form-control datepicker-here" data-timepicker="true" data-time-format='hh:ii'
                                   placeholder="To Date" value="<?= isset($to) ? $to : ''; ?>">
                        </div>
                        <div class="col-md-1">
                            <button type="button" name="search" class="btn btn-success">Search</button>
                        </div>
                        <div class="col-md-1 ">
                            <button type="submit" name="btnExportcsv" class="btn btn-warning ">Export to CSV</button>
                        </div>
                    </div>
                    <div>
                        <strong>Total</strong>
                        <?= $page->total_items ?> records
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered">
                            <thead class="table_header">
                            <tr class="headings">
                                <th width="50px" class="column-title">ID</th>
                                <th class="column-title">First Name</th>
                                <th class="column-title">Last Name</th>
                                <th class="column-title">User Email</th>
                                <th class="column-title">User Telephone</th>
                                <th width="160px" class="column-title">Insert Time</th>
                                <th width="50px" class="column-title">Is Subscribe</th>
                                <th width="120px" class="column-title">Sent Email</th>
                                <th width="50px" class="column-title no-link last"><span class="nobr">Action </span>
                                </th>
                            </tr>
                            </thead>
                            <tbody class="tb_body">
                            <?php foreach ($page->items as $item) {
                                /**
                                /*@var Forexceccom\Models\ForexcecLeadform $item
                                 */
                                ?>
                                <tr>
                                    <td><?= $item->getLeadformId(); ?></td>
                                    <td><?= $item->getLeadformFirstName(); ?></td>
                                    <td><?= $item->getLeadformLastName(); ?></td>
                                    <td><?= $item->getLeadformEmail(); ?></td>
                                    <td><?= $item->getLeadformNumber(); ?>
                                        <?php if ($item->getLeadformNumberVerify() == 'Y') { ?>
                                            - <strong style="color: #5cb85c"> Verified</strong>
                                        <?php } ?>
                                    </td>
                                    <td><?= $this->my->formatDateTime($item->getLeadformInsertTime(),false); ?></td>

                                        <?php
                                        $send_log = \Forexceccom\Repositories\SentEmailLog::findFirstByOnlyEmail($item->getLeadformEmail());
                                        if ($send_log) {
                                            $status = $send_log->getSentStatus();

                                            $is_subscribe = $send_log->getSentIsSubscribe();
                                            if ($is_subscribe == "Y") {
                                                $class_subcribe = "success";
                                            } else {
                                                $class_subcribe = 'danger';
                                            }
                                        } else {
                                            $status = 'processing';

                                            $is_subscribe = "";
                                            $class_subcribe = "";
                                        }
                                        if ($status == 'processing') {
                                            $class = 'info';
                                        } else {
                                            $class = 'success';
                                        }
                                        $is_subscribe = $send_log->getSentIsSubscribe();
                                        if ($is_subscribe == "Y") {
                                            $class_subcribe = "success";
                                        } else {
                                            $class_subcribe = 'danger';
                                        }
                                        ?>
                                    <td class="text-center" >
                                        <span class="  label label-<?php echo $class_subcribe; ?>"><?php echo $is_subscribe; ?></span>
                                    </td>
                                    <td class="text-center" >
                                        <span class="label label-<?php echo $class; ?>"><?php echo $status; ?></span>
                                    </td>
                                    <td class="last">
                                    <a class="btn btn-primary btn-xs margin-0"  href="<?php echo $this->url->get("/view-leadform?id=".$item->getLeadformId()); ?>">View</a>
                                    </td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="clearfix"></div>
                    <div class="row">
                        <div class="col-md-6 pull-right">
                            <?php if ($page->total_pages > 1) { ?>
                                <nav class="paginate-footer">
                                    <?php if ($urlPage != "?") $urlPage .= "&";
                                    $urlPage .= "page=";
                                    echo $this->my->renderPagination($urlPage, $page->current, $page->total_pages, 2);
                                    ?>
                                </nav>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script>
    $(document).ready(function () {
        $('button[name=search]').click(function () {
            $('form[name=form-type]').prop('action', '<?= $this->url->get('/list-leadform'); ?>');
            $('form[name=form-type]').submit();
        });
    });
</script>

