<?php
/**
 * @var \Forexceccom\Models\ForexcecLeadform $leadFormModel
 */
?>
<div class="page-title">
    <div class="title_left">
        <h3 class="type-title">Lead Form Detail #<?= $this->my->formatLeadFormID($leadFormModel->getLeadformInsertTime(), $leadFormModel->getLeadformId()); ?></h3>
    </div>
</div>
<div class="clearfix"></div>
<p id="alertSubscribe"></p>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br />
                <h3>Lead Form Information:</h3>

                <table class="table table-hover table-striped table-responsive table-bordered table-activity">
                    <tbody>
                    <tr>
                        <td style="width: 250px" >User Name</td>
                        <td><?= $leadFormModel->getLeadformFirstName(); ?></td>
                    </tr>
                    <tr>
                        <td>User Email</td>
                        <td><?= $leadFormModel->getLeadformEmail(); ?></td>
                    </tr>
                    <tr>
                        <td>User Telephone</td>
                        <td><?= $leadFormModel->getLeadformNumber(); ?></td>
                    </tr>
                    <tr>
                        <td>Number Verify</td>           
                        <td>
                            <?php $class_checked = ($leadFormModel->getLeadformNumberVerify() == 'Y') ? 'success' : 'danger' ; ?>
                            <span class="badge badge-<?= $class_checked; ?>"><?= $leadFormModel->getLeadformNumberVerify(); ?></span>
                        </td>
                    </tr>
                    <tr>
                        <td>Nationality</td>
                        <td><?= $leadFormModel->getLeadformNationality(); ?></td>
                    </tr>
                    <tr>
                        <td>Account Type</td>
                        <td><?= $leadFormModel->getLeadformAccountType(); ?></td>
                    </tr>
                    <tr>
                        <td>Insert Time</td>
                        <td><?= $this->my->formatDateTime($leadFormModel->getLeadformInsertTime(),false); ?></td>
                    </tr>

                    <?php
                    use Forexceccom\Repositories\SentEmailLog;
                    use Forexceccom\Models\ForexcecSentEmailLog;
                    $log_email = SentEmailLog::findFirstByEmail($leadFormModel->getLeadformEmail(),ForexcecSentEmailLog::FORM_LEADFORM);
                    $is_subscribe = $log_email ? $log_email->getSentIsSubscribe() : "";
                    $select_subscribe = SentEmailLog::getComboboxSubscribe($is_subscribe);
                    ?>
                    <tr>
                        <td>Is Subscribe</td>
                        <td>
                            <select id="slSubscribe" name="slSubscribe" style="width: 50px">
                                <?= isset($select_subscribe) ? $select_subscribe : "" ?>
                            </select>
                        </td>
                    </tr>
                    </tbody>
                </table>

                <?php
                    $activity = $leadFormModel->activity;
                    if ($activity) { ?>
                    <h3>Location Information:</h3>
                    <table class="table table-hover table-striped table-responsive table-bordered table-activity">
                        <tbody>
                        <tr>
                            <td style="width: 250px" >IP Address</td>
                            <td><?= $activity->getActivityIp(); ?></td>
                        </tr>
                        </tbody>
                    </table>
                <?php } ?>

                <?php 
                    if ($activity){
                        $userAgent = $activity->userAgent;
                    }
                    if (isset($userAgent)) { ?>
                    <h3>Device Information:</h3>
                    <table class="table table-hover table-striped table-responsive table-bordered table-activity">
                        <tbody>
                        <tr>
                            <td style="width: 250px" >Checked</td>
                            <td>
                                <?php $class_checked = ($userAgent->getAgentChecked() == 'Y') ? 'success' : 'danger' ; ?>
                                <span class="badge badge-<?= $class_checked; ?>"><?= $userAgent->getAgentChecked(); ?></span>
                            </td>
                        </tr>
                        <tr>
                            <td>Hardware Type</td>
                            <td><?= $userAgent->getAgentHardwareType(); ?></td>
                        </tr>
                        <tr>
                            <td>Operating System Name</td>
                            <td><?= $userAgent->getAgentOperatingSystemName(); ?></td>
                        </tr>
                        <tr>
                            <td>Software Sub Type</td>
                            <td><?= $userAgent->getAgentSoftwareSubType(); ?></td>
                        </tr>
                        <tr>
                            <td>Simple Sub Description</td>
                            <td><?= $userAgent->getAgentSimpleSubDescriptionString(); ?></td>
                        </tr>
                        <tr>
                            <td>Simple Browser</td>
                            <td><?= $userAgent->getAgentSimpleBrowserString(); ?></td>
                        </tr>
                        <tr>
                            <td>Browser Version</td>
                            <td><?= $userAgent->getAgentBrowserVersion(); ?></td>
                        </tr>
                        <tr>
                            <td>Software Type</td>
                            <td><?= $userAgent->getAgentSoftwareType(); ?></td>
                        </tr>
                        <tr>
                            <td>Extra Info</td>
                            <td><?= $userAgent->getAgentExtraInfo(); ?></td>
                        </tr>
                        <tr>
                            <td>Operating Platform</td>
                            <td><?= $userAgent->getAgentOperatingPlatform(); ?></td>
                        </tr>
                        <tr>
                            <td>Extra Info Table</td>
                            <td><?= $userAgent->getAgentExtraInfoTable(); ?></td>
                        </tr>
                        <tr>
                            <td>Layout Engine Name</td>
                            <td><?= $userAgent->getAgentLayoutEngineName(); ?></td>
                        </tr>
                        <tr>
                            <td>Operating System Flavour Code</td>
                            <td><?= $userAgent->getAgentOperatingSystemFlavourCode(); ?></td>
                        </tr>
                        <tr>
                            <td>Detected Addons</td>
                            <td><?= $userAgent->getAgentDetectedAddons(); ?></td>
                        </tr>
                        <tr>
                            <td>Operating System Flavour</td>
                            <td><?= $userAgent->getAgentOperatingSystemFlavour(); ?></td>
                        </tr>
                        <tr>
                            <td>Operating System Frameworks</td>
                            <td><?= $userAgent->getAgentOperatingSystemFrameworks(); ?></td>
                        </tr>
                        <tr>
                            <td>Browser Name Code</td>
                            <td><?= $userAgent->getAgentBrowserNameCode(); ?></td>
                        </tr>
                        <tr>
                            <td>Simple Minor</td>
                            <td><?= $userAgent->getAgentSimpleMinor(); ?></td>
                        </tr>
                        <tr>
                            <td>Simple Operating Platform</td>
                            <td><?= $userAgent->getAgentSimpleOperatingPlatformString(); ?></td>
                        </tr>
                        <tr>
                            <td>Abusive</td>
                            <td><?= $userAgent->getAgentIsAbusive(); ?></td>
                        </tr>
                        <tr>
                            <td>Simple Medium</td>
                            <td><?= $userAgent->getAgentSimpleMedium(); ?></td>
                        </tr>
                        <tr>
                            <td>Layout Engine Version</td>
                            <td><?= $userAgent->getAgentLayoutEngineVersion(); ?></td>
                        </tr>
                        <tr>
                            <td>Browser Capabilities</td>
                            <td><?= $userAgent->getAgentBrowserCapabilities(); ?></td>
                        </tr>
                        <tr>
                            <td>Operating Platform Vendor Name</td>
                            <td><?= $userAgent->getAgentOperatingPlatformVendorName(); ?></td>
                        </tr>
                        <tr>
                            <td>Operating System</td>
                            <td><?= $userAgent->getAgentOperatingSystem(); ?></td>
                        </tr>
                        <tr>
                            <td>Hardware Architecture</td>
                            <td><?= $userAgent->getAgentHardwareArchitecture(); ?></td>
                        </tr>
                        <tr>
                            <td>Operating System Version Full</td>
                            <td><?= $userAgent->getAgentOperatingSystemVersionFull(); ?></td>
                        </tr>
                        <tr>
                            <td>Operating Platform Code</td>
                            <td><?= $userAgent->getAgentOperatingPlatformCode(); ?></td>
                        </tr>
                        <tr>
                            <td>Browser Name</td>
                            <td><?= $userAgent->getAgentBrowserName(); ?></td>
                        </tr>
                        <tr>
                            <td>Operating System Name Code</td>
                            <td><?= $userAgent->getAgentOperatingSystemNameCode(); ?></td>
                        </tr>
                        <tr>
                            <td>User Agent</td>
                            <td><?= $userAgent->getAgentUserAgent(); ?></td>
                        </tr>
                        <tr>
                            <td>Simple Major</td>
                            <td><?= $userAgent->getAgentSimpleMajor(); ?></td>
                        </tr>
                        <tr>
                            <td>Browser Version Full</td>
                            <td><?= $userAgent->getAgentBrowserVersionFull(); ?></td>
                        </tr>
                        <tr>
                            <td>Browser</td>
                            <td><?= $userAgent->getAgentBrowser(); ?></td>
                        </tr>
                        </tbody>
                    </table>
                <?php } ?>
                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-1">
                    <a class="btn btn-primary" href="<?= $this->url->get("/list-leadform"); ?>">Back List</a>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $('#slSubscribe').on('change',function () {
        var is_subscribe = $('#slSubscribe').val();
        var email = "<?=$leadFormModel->getLeadformEmail()?>";
        $.ajax({
            url: "<?php echo $this->url->get('/change-is-subscribe'); ?>",
            type: 'POST',
            dataType: "JSON",
            data: {is_subscribe: is_subscribe, email: email},
            success: function (data) {
                if (data.status == 'success') {
                    $('#alertSubscribe').addClass('alert alert-success');
                    $('#alertSubscribe').html('Change Subscribe success.');
                } else {
                    $('#alertSubscribe').addClass('alert alert-danger');
                    $('#alertSubscribe').html(data.message);
                }
            }
        });
    })
</script>
