<div class="page-title">
    <div class="title_left" style="width: 100% ;">
        <h3 class="type-title">Countries for <?php echo isset($channel_name) ? $channel_name : ''?></h3>
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2 class="form_title">List countries</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br />
                <form name="payment-mid-form" id="payment-mid-form" data-parsley-validate class="form-horizontal form-label-left" method="post">
                    <div class="form-group">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <?php echo isset($country) ? $country : ""; ?>
                        </div>
                    </div>

                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button type="button" class="btn btn-info" name="btnCheckAll" >Check All</button>
                            <button type="button" class="btn btn-warning" name="btnUncheck" >Uncheck</button>
                            <button name="submit" type="submit" class="btn btn-success">Save</button>
                            <a class="btn btn-primary" href="<?= $this->url->get('/list-communication-channel') ?>">Cancel</a>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
<script>
    $( document ).ready(function() {
        $('button[name=btnUncheck]').click(function() {
            $('.check').prop('checked', false);
        });
        $('button[name=btnCheckAll]').click(function() {
            $('.check').prop('checked', true);
        });
    });
</script>