<?php
/**
 * @var \Dsbcfcom\Models\DsbcfPayment $payment
 */

use Dsbcfcom\Repositories\Payment;
use Dsbcfcom\Models\DsbcfPayment;

$id_format = $this->my->formatPaymentID($payment->getPaymentInsertDate(), $payment->getPaymentId()); ?>
<div class="page-title">
    <div class="title_left">
        <h3 class="type-title">Payment Details #<?php echo $id_format; ?></h3>
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br/>
                <h3>Payment Details </h3>
                <?php
                $status = '';
                if ($payment->getPaymentStatus() == 'Pending') {
                    $status = 'danger';
                } else if ($payment->getPaymentStatus() == 'Success') {
                    $status = 'success';
                }
                ?>
                <table class="table table-hover table-striped table-responsive table-bordered table-activity">
                    <tbody>
                    <tr>
                        <strong>Payment ID : #<?php echo $id_format; ?></strong>
                        <p>This payment have status <strong
                                    class="text-<?php echo $status ?>"><?php echo $payment->getPaymentStatus(); ?></strong>
                        </p>
                    </tr>
                    <tr>
                        <td>Insert Time</td>
                        <td><?php
                            echo $this->my->formatDateTime($payment->getPaymentInsertDate(), false);
                            ?></td>
                    </tr>
                    <?php if (!empty($payment->getPaymentDate()) && $payment->getPaymentDate() > 0 && $payment->getPaymentStatus() == 'Success') { ?>
                        <tr>
                            <td>Payment Date</td>
                            <td><?php
                                echo $this->my->formatDateTime($payment->getPaymentDate(), false);
                                ?></td>
                        </tr>
                    <?php } ?>
                    <tr>
                        <td>Amount</td>
                        <td>
                            <?php $selectCurrency = $payment->getPaymentOrderCurrency();
                            $currencyData['code'] = $selectCurrency;
                            $currencyDataFromDatabase = \Forexceccom\Models\ForexcecCurrency::findFirst("currency_code = '$selectCurrency'");
                            if ($currencyDataFromDatabase) {
                                $currencyData['symbol'] = $currencyDataFromDatabase->getCurrencySymbolLeft();
                            } else {
                                $currencyData['symbol'] = $this->globalVariable->mainCurrency;
                            }
                            if ($selectCurrency) echo $currencyData['symbol'] . ' ' . $this->my->formatUSD($payment->getPaymentOrderAmount()); else echo $currencyData['symbol'] . ' ' . $this->my->formatUSD($payment->getPaymentAmount());
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <td>Exchange rate fixed at </td>
                        <td>
                            <?php echo '1 '. $payment->getPaymentOrderCurrency(). ' = '.round($payment->getPaymentExrate(),3).' '.$payment->getPaymentCurrency().', updated on: '. date('M/d/Y', $payment->getPaymentExrateDate())?>
                        </td>
                    </tr>
                    <?php if($currencyInfo) { ?>
                    <tr>
                        <td>Equivalent of USD </td>
                        <td>
                            <?php echo $currencyInfo->getCurrencySymbolLeft().' '.$this->my->formatUSD(round($payment->getPaymentOrderAmount()*$payment->getPaymentExrate(),2))?>
                        </td>
                    </tr>
                     <?php } ?>
                    <tr>
                        <td>Method</td>
                        <td><?php echo $payment->getPaymentMethod();
                            if($payment->payment_cardtype){
                                echo " - ".$payment->payment_cardtype;
                            }
                            if ($payment->payment_isenrolled3d == 'Y') {
                                if ($payment->payment_ispassed3d == 'Y') {
                                    echo ' (Passed 3D Secure)';
                                }
                                else {
                                    echo ' (Failed 3D Secure)';
                                }
                            }else if($payment->payment_isenrolled3d == 'N'){
                                echo ' (None 3D Secure)';
                            }
                            ?></td>
                    </tr>
                    <?php if ($payment->getPaymentStatus() == 'Fail' && !empty($payment->getPaymentFailReason())) { ?>
                        <tr>
                            <td>Reason fail</td>
                            <td><?php echo $payment->getPaymentFailReason(); ?></td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>

                <h3>User Details </h3>
                <?php
                $userData = \Forexceccom\Models\ForexcecUser::findFirstById($payment->getPaymentUserId());
                ?>
                <table class="table table-hover table-striped table-responsive table-bordered table-activity">
                    <tbody>
                    <tr>
                        <td style="width: 350px">
                            Full name
                        </td>
                        <td class="">
                            <?php echo $userData ? $userData->getUserName() : ''; ?>
                        </td>
                    </tr>

                    <tr>
                        <td style="width: 350px">
                            Email
                        </td>
                        <td class="">
                            <?php echo ($userData) ? $userData->getUserEmail() : ''; ?>
                        </td>
                    </tr>

                    </tbody>
                </table>
                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-1">
                    <a class="btn btn-primary" href="<?php echo $this->url->get("/list-make-payment"); ?>">Back
                        List</a>
                </div>
            </div>
        </div>
    </div>
</div>