<div class="page-title">
    <div class="title_left">
        <h3>Translate Tool for admin.forexcec.com</h3>
    </div>
</div>
<?php if (isset($msg_result['status']) && isset($msg_result['msg']) && is_string($msg_result['msg'])) { ?>
    <div class="clearfix"></div>
    <div class="alert alert-<?php echo $msg_result['status'] ?> alert-dismissible fade in" role="alert">
        <?php echo $msg_result['msg']; ?>
    </div>
<?php } ?>
<div class="clearfix"></div>
<form class="translate-form" name="translate-form" method="post">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <div class="row ">
                        <div class="col-md-6 form-group">
                            <label>Translate from</label>
                            <select class="form-control <?php echo (isset($msg_result['status']) && $msg_result['status'] == 'border-red') ? ' border-red' : '' ?>" name="slLanguageFrom" id="slLanguageFrom">
                                <option value="">Select 1 Language</option>
                                <?php echo isset($slLanguageFrom) ? $slLanguageFrom : '' ?>
                            </select>
                            <p class="text-danger msg-slc-from"><?php echo isset($msg_result['msg']['message_language_from']) ? $msg_result['msg']['message_language_from'] : '' ?></p>
                        </div>
                        <div class="col-md-6 form-group">
                            <label>Translate to</label>
                            <select class="form-control <?php echo (isset($msg_result['status']) && $msg_result['status'] == 'border-red') ? ' border-red' : '' ?>" name="slLanguageTo" id="slLanguageTo">
                                <option value="">Select 1 Language</option>
                                <?php echo isset($slLanguageTo) ? $slLanguageTo : '' ?>
                            </select>
                            <p class="text-danger msg-slc-to"><?php echo isset($msg_result['msg']['message_language_to']) ? $msg_result['msg']['message_language_to'] : '' ?></p>
                        </div>
                        <div class="clearfix"></div>
                        <div class="col-md-6 form-group">
                            <textarea class="form-control <?php echo (isset($msg_result['status']) && $msg_result['status'] == 'border-red') ? ' border-red' : '' ?>" id="txtFrom" name="txtFrom" style="height: 212px;"><?php echo isset($msg_result["txtFrom"]) ? $msg_result["txtFrom"] : '';  ?></textarea>
                            <p class="text-danger msg-from"><?php echo isset($msg_result['msg']['message_from']) ? $msg_result['msg']['message_from'] : '' ?></p>
                        </div>
                        <div class="col-md-6 form-group">
                            <textarea class="form-control" id="txtTo" name="txtTo" style="height: 212px;"><?php echo isset($msg_result['data']) ? $msg_result['data'] : '' ?></textarea>
                            <p class="text-danger msg-to"></p>
                        </div>
                        <div class="clearfix"></div>
                        <div class="col-md-6 form-group text-right">
                            <button type="submit" name="translate" class="btn btn-success" style="width: 200px">Translate</button>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
</form>
<script>
    $(document).ready(function () {
        $("form[name=translate-form]").submit(function (event) {
            var valid = true;
            if($('textarea[name=txtFrom]').val() == '') {
                $('.msg-from').text('This field is required.');
                $('#txtFrom').addClass("border-red");
                valid = false;
            } else {
                $('.msg-from').text('');
                $('#txtFrom').removeClass("border-red");
            }
            if ($('select[name=slLanguageFrom]').val() == '') {
                $('.msg-slc-from').text('This field is required.');
                $('#slLanguageFrom').addClass("border-red");
                valid = false;
            } else {
                $('.msg-slc-from').text('');
                $('#slLanguageFrom').removeClass("border-red");
            }
            if ($('select[name=slLanguageTo]').val() == '') {
                $('.msg-slc-to').text('This field is required.');
                $('#slLanguageTo').addClass("border-red");
                valid = false;
            } else {
                $('.msg-slc-to').text('');
                $('#slLanguageTo').removeClass("border-red");
            }
            if($('select[name=slLanguageFrom]').val() != '' && $('select[name=slLanguageTo]').val() != '') {
                if($('select[name=slLanguageFrom]').val()==$('select[name=slLanguageTo]').val()){
                    $('.msg-slc-to').text('Language is duplicate. Please try again.');
                    $('#slLanguageTo').addClass("border-red");
                    valid = false;
                } else {
                    $('.msg-slc-to').text('');
                    $('#slLanguageTo').removeClass("border-red");
                }
            }
            if(!valid) {
                event.preventDefault();
            }
            if( valid ) {
                $('button[name=translate]').prop('disabled', true);
            }
        });
    });
</script>