<?php
$urlPage = "?";
if(strlen($this->dispatcher->getParam("txtSearch"))> 0){
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtSearch" => $this->dispatcher->getParam("txtSearch")));
}
if($this->dispatcher->getParam("slcLanguage") != ""){
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("slcLanguage" => $this->dispatcher->getParam("slcLanguage")));
}
if($this->dispatcher->getParam("slcType") != ""){
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("slcType" => $this->dispatcher->getParam("slcType")));
}
?>
<h4 class="text-danger">NOTE: Only new insert if it not exist in table ( NOT UPDATE)</h4>
<div class="page-title">
    <div class="title_left">
        <h3>Translate</h3>
    </div>
</div>
<?php if(isset($msg_result))  {?>
<div class="clearfix"></div>
<div  class="alert alert-<?php echo $msg_result['status']?> alert-dismissible fade in" role="alert">
    <?php echo $msg_result['msg']; ?>
</div>
<?php } ?>
<div class="clearfix"></div>
<form class="searchForm" name="form-translate" method="post" action="">
    <?php $keyword = $this->dispatcher->getParam("txtSearch");
    ?>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <div class="row ">
                        <div class="col-md-1">
                            <h2 class="">Keyword</h2>
                        </div>
                        <div class="col-md-2">
                            <input maxlength="255" class="form-control" type="text" name="txtSearch" placeholder="ID, Name " value="<?php echo isset($keyword) ? $keyword : ""; ?>">
                        </div>
                        <h2 class="align-center">Language</h2>
                        <div class="col-md-2">
                            <select class="form-control" name="slcLanguage" id="slcLanguage">
                                <option value="0">All Language</option>
                                <?php echo isset($select_lang)? $select_lang : '' ?>
                            </select>
                        </div>
                           
                        <div class="col-md-1">
                            <button type="button" name="search" class="btn btn-success">Search</button>
                        </div>
                        <div class="col-md-1 pull-right text-right">
                            <a class="btn btn-info" href="<?php echo $this->url->get("/create-translate"); ?>">Add New</a>
                        </div>
                    </div>
                    <div >
                        <strong>Total</strong>
                        <?php echo $list_translate->total_items ?> records
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered">
                            <thead class="table_header" >
                            <tr class="headings">
                                <th style="text-align: left" width="50px"><label class="container_checkbox"><input type="checkbox" id="checkboxAll"><span class="checkmark_checkbox"></span></label></th>
                                <th width="50px" class="column-title">ID </th>
                                <th width="50px"class="column-title">Language </th>
                                <th class="column-title">Table Translate</th>
                                <th width="" class="column-title">Reason</th>
                                <th width="50px" class="column-title">Cron ID </th>
                                <th width="50px" class="column-title">Cron Key</th>
                                <th width="50px" class="column-title">Order </th>
                                <th width="50px" class="column-title">Insert time </th>
                                <th width="50px" class="column-title">Active </th>
                                <th width="120px" class="column-title no-link last"><span class="nobr">Action</span></th>
                            </tr>
                            </thead>

                            <tbody class="tb_body">
                            <?php foreach ($list_translate->items as $item) { 
                                /** @var \Forexceccom\Models\ForexcecTableTranslate $item */
                                ?>
                                <tr >
                                    <td><label class="container_checkbox"><input class="check" name="item[]" value="<?php echo $item->getTranslateId() ?>" type="checkbox"><span class="checkmark_checkbox"></span></label></td>
                                    <td><?php echo $item->getTranslateId() ?></td>
                                    <td><?php echo $item->getTranslateLanguage()?></td>
                                    <td>
                                        <textarea style="width: 100% "><?php echo $item->getTranslateTable() ?></textarea>
                                    </td>

                                    <td class="text-center"><?php echo $item->getTranslateReason() ?></td>
                                    <td class="text-center"><?php echo $item->getTranslateCronId() ?></td>
                                    <td class="text-center"><?php echo $item->getTranslateCron() ?></td>
                                    <td class="text-center"><?php echo $item->getTranslateOrder() ?></td>
                                    <td class=" "><?php echo $this->my->formatDateTime($item->getTranslateInsertTime(),false)?></td>

                                    <td class="text-center" data-title="Active">
                                        <?php
                                        $status = $item->getTranslateActive();
                                        if ($status == "Y"){
                                            $status_title = "Processing";
                                            $classStatus = "success";
                                        }else{
                                            $status_title = "Done";
                                            $classStatus = "danger";
                                        }
                                        ?>
                                        <span class="label label-<?php echo $classStatus; ?>"><?php echo $status_title; ?></span>
                                    </td>
                                    <td class="text-center">
                                        <a class="btn btn-primary btn-xs margin-0"   href="<?php echo $this->url->get("/edit-translate?id=".$item->getTranslateId()); ?> ">View</a>
                                        <a class="btn btn-warning btn-xs margin-0" href="<?php echo $this->url->get("/detail-cron?id=" . $item->getTranslateCronId()."&slLanguage=" . $item->getTranslateLanguage()); ?> ">Cron</a>
                                    </td>
                                </tr>

                            <?php }?>
                            </tbody>
                        </table>

                    </div>
                    <div class="clearfix"></div>
                    <div class="row">
                        <div class="col-md-6 ">
                            <label for="slAction">With Selected:</label>
                            <select class="form-control" id="slcAction" name="slcAction" style="display: inline-block;width: 40%">
                                <option value="" selected >Please select</option>
                                <option value="drop">Drop</option>
                            </select>
                        </div>
                        <div class="col-md-6">
                            <?php if($list_translate->total_pages > 1) {?>
                                <nav class="paginate-footer">
                                    <?php  if($urlPage != "?") $urlPage .= "&";
                                    $urlPage .= "page=";
                                    echo $this->my->renderPagination($urlPage, $list_translate->current, $list_translate->total_pages, 2);
                                    ?>
                                </nav>
                            <?php }?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script>
    $(document).ready(function(){
        $('button[name=search]').click(function() {
            $('form[name=form-translate]').prop('action','<?php echo $this->url->get('/list-translate'); ?>');
            $('form[name=form-translate]').submit();
        });

        $('.delete-all').click(function(){
            $('form[name=form-translate]').prop('action','<?php echo $this->url->get('/delete-translate'); ?>');
            $('form[name=form-translate]').submit();
        });
    });
</script>