<?php
if (isset($role_function)) {
    $pre = 'backend';
    $menu_active = 'class="active"';
    $menu_sub_active = 'style="display: block;"';
    $menu_sub_sub_active = 'class="current-page"';
    $role = new \Score\Repositories\Role();
    $controllers = \Score\Models\ForexcecRole::getControllers();

    $setting = isset($controllers['setting']) ? $controllers['setting'] : array();
    $check_setting = ($role::checkMenu($role_function, $setting)) ? true : false;
    $check_setting_sub = ($role::checkMenuSub($setting, $this->dispatcher->getControllerName())) ? true : false;

    $content = isset($controllers['content']) ? $controllers['content'] : array();
    $check_content = ($role::checkMenu($role_function, $content)) ? true : false;
    $check_content_sub = ($role::checkMenuSub($content, $this->dispatcher->getControllerName())) ? true : false;

    $translate = isset($controllers['translate'])?$controllers['translate']:array();
    $check_translate =  ($role::checkMenu($role_function,$translate))?true:false;
    $check_translate_sub =  ($role::checkMenuSub($translate,$this->dispatcher->getControllerName()))?true:false;

    $register = isset($controllers['register'])?$controllers['register']:array();
    $check_register =  ($role::checkMenu($role_function,$register))?true:false;
    $check_register_sub =  ($role::checkMenuSub($register,$this->dispatcher->getControllerName()))?true:false;
}
?>
<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
            <a href="<?php echo $this->url->get("/"); ?>" class="site_title"><i class="fa fa-institution"></i>
                <span>ForexCEC </span></a>
        </div>
        <div class="clearfix"></div>
        <br/>
        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <ul class="nav side-menu">
                    <?php if ($check_content) { ?>
                        <li <?php echo ($check_content_sub) ? $menu_active : ""; ?> >
                            <a><i class="fa fa-database"></i>
                                Content <span class="fa fa-chevron-down"></span></a>
                            <ul class="nav child_menu" <?php echo ($check_content_sub) ? $menu_sub_active : ""; ?> >
                                <?php if ($role::checkiMenuItem($role_function, "type")) { ?>
                                    <li <?php echo ($this->dispatcher->getControllerName() === "type") ? $menu_sub_sub_active : ""; ?> >
                                        <a href="<?php echo $this->url->get("/list-type"); ?>">Type</a>
                                    </li>
                                <?php } ?>
                                <?php if ($role::checkiMenuItem($role_function, "article")) { ?>
                                    <li <?php echo ($this->dispatcher->getControllerName() === "article") ? $menu_sub_sub_active : ""; ?> >
                                        <a href="<?php echo $this->url->get("/list-article"); ?>">Article</a>
                                    </li>
                                <?php } ?>
                                <?php if ($role::checkiMenuItem($role_function, "banner")) { ?>
                                    <li <?php echo ($this->dispatcher->getControllerName() === "banner") ? $menu_sub_sub_active : ""; ?> >
                                        <a href="<?php echo $this->url->get("/list-banner"); ?>">Banner</a>
                                    </li>
                                <?php } ?>
                                <?php if ($role::checkiMenuItem($role_function, "country")) { ?>
                                    <li <?php echo ($this->dispatcher->getControllerName() === "country") ? $menu_sub_sub_active : ""; ?> >
                                        <a href="<?php echo $this->url->get("/list-country"); ?>">Country</a>
                                    </li>
                                <?php } ?>
                                <?php if ($role::checkiMenuItem($role_function, "glossary")) { ?>
                                    <li <?php echo ($this->dispatcher->getControllerName() === "glossary") ? $menu_sub_sub_active : ""; ?> >
                                        <a href="<?php echo $this->url->get("/list-glossary"); ?>">Glossary</a>
                                    </li>
                                <?php } ?>
                                <?php if ($role::checkiMenuItem($role_function, "office")) { ?>
                                    <li <?php echo ($this->dispatcher->getControllerName() === "office") ? $menu_sub_sub_active : ""; ?> >
                                        <a href="<?php echo $this->url->get("/list-office"); ?>">Office</a>
                                    </li>
                                <?php } ?>
                                <?php if ($role::checkiMenuItem($role_function, "communicationchannel")) { ?>
                                    <li <?php echo ($this->dispatcher->getControllerName() === "communicationchannel") ? $menu_sub_sub_active : ""; ?> >
                                        <a href="<?php echo $this->url->get("/list-communication-channel"); ?>">Communication
                                            Channel</a>
                                    </li>
                                <?php } ?>
                            </ul>
                        </li>
                    <?php } ?>

                    <?php if ($check_setting) { ?>
                    <li <?php echo ($check_setting_sub) ? $menu_active : ""; ?> >
                        <a><i class="fa fa-sliders"></i>
                            Settings <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu" <?php echo ($check_setting_sub) ? $menu_sub_active : ""; ?> >
                            <?php if ($role::checkiMenuItem($role_function, "page")) { ?>
                                <li <?php echo ($this->dispatcher->getControllerName() === "page") ? $menu_sub_sub_active : ""; ?> >
                                    <a href="<?php echo $this->url->get("/list-page"); ?>">Page</a>
                                </li>
                            <?php } ?>
                            <?php if ($role::checkiMenuItem($role_function, "role")) { ?>
                                <li <?php echo ($this->dispatcher->getControllerName() === "role") ? $menu_sub_sub_active : ""; ?> >
                                    <a href="<?php echo $this->url->get("/list-role"); ?>">Role</a>
                                </li>
                            <?php } ?>
                            <?php if ($role::checkiMenuItem($role_function, "language")) { ?>
                                <li <?php echo ($this->dispatcher->getControllerName() === "language") ? $menu_sub_sub_active : ""; ?> >
                                    <a href="<?php echo $this->url->get("/list-language"); ?>">Language</a>
                                </li>
                            <?php } ?>
                            <?php if ($role::checkiMenuItem($role_function, "location")) { ?>
                                <li <?php echo ($this->dispatcher->getControllerName() === "location") ? $menu_sub_sub_active : ""; ?> >
                                    <a href="<?php echo $this->url->get("/list-location"); ?>">Location</a>
                                </li>
                            <?php } ?>
                            <?php if ($role::checkiMenuItem($role_function, "emailtemplate")) { ?>
                                <li <?php echo ($this->dispatcher->getControllerName() === "emailtemplate") ? $menu_sub_sub_active : ""; ?> >
                                    <a href="<?php echo $this->url->get("/list-emailtemplate"); ?>">Template
                                        Email</a>
                                </li>
                            <?php } ?>
                            <?php if ($role::checkiMenuItem($role_function, "templateautoemail")) { ?>
                                <li <?php echo ($this->dispatcher->getControllerName() === "templateautoemail") ? $menu_sub_sub_active : ""; ?> >
                                    <a href="<?php echo $this->url->get("/list-template-auto-email"); ?>">Template Auto
                                        Email</a>
                                </li>
                            <?php } ?>
                            <?php if ($role::checkiMenuItem($role_function, "config")) { ?>
                                <li <?php echo ($this->dispatcher->getControllerName() === "config") ? $menu_sub_sub_active : ""; ?> >
                                    <a href="<?php echo $this->url->get("/list-config"); ?>">Config</a>
                                </li>
                            <?php } ?>
                        </ul>
                    </li>
                    <?php } ?>
                    <?php if($check_register){ ?>
                        <li <?php echo ($check_register_sub)?$menu_active:""; ?> ><a><i class="fa fa-registered"></i> Register <span class="fa fa-chevron-down"></span></a>
                            <ul class="nav child_menu" <?php echo ($check_register_sub)?$menu_sub_active:""; ?> >
                                <?php if($role::checkiMenuItem($role_function,"registerpage")) { ?>
                                    <li <?php echo ($this->dispatcher->getControllerName() === "registerpage")?$menu_sub_sub_active:""; ?> >
                                        <a href="<?php echo $this->url->get("/list-register-page");?>">Register Page</a>
                                    </li>
                                <?php } ?>
                    
                            </ul>
                        </li>
                    <?php } ?>
                    <?php if ($role::checkiMenuItem($role_function, "cloudupload")) { ?>
                        <li <?php echo ($this->dispatcher->getControllerName() == "cloudupload") ? $menu_active : ""; ?>><a
                                    href="<?php echo $this->url->get("/cloud-upload"); ?>"><i
                                        class="fa fa-file"></i>Upload File</a></li>
                    <?php } ?>
                    <?php if ($role::checkiMenuItem($role_function, "formupload")) { ?>
                        <li <?php echo ($this->dispatcher->getControllerName() == "formupload") ? $menu_active : ""; ?>><a
                                    href="<?php echo $this->url->get("/dashboard/form-upload"); ?>"><i
                                        class="fa fa-cloud-upload"></i>Upload Documents</a></li>
                    <?php } ?>
                    <?php if ($role::checkiMenuItem($role_function, "user")) { ?>
                        <li <?php echo ($this->dispatcher->getControllerName() == "user") ? $menu_active : ""; ?>><a
                                    href="<?php echo $this->url->get("/list-user"); ?>"><i
                                        class="fa fa-user"></i>User</a></li>
                    <?php } ?>

                    <?php if ($role::checkiMenuItem($role_function, "partnership")) { ?>
                        <li <?php echo ($this->dispatcher->getControllerName() === "partnership") ? $menu_active : ""; ?> ><a
                                    href="<?php echo $this->url->get("/list-partnership"); ?>"><i
                                        class="fa fa-users"></i>Partnership</a></li>
                    <?php } ?>
                    <?php if ($role::checkiMenuItem($role_function, "leadform")) { ?>
                        <li <?php echo ($this->dispatcher->getControllerName() === "leadform") ? $menu_active : ""; ?> ><a
                                    href="<?php echo $this->url->get("/list-leadform"); ?>"><i
                                        class="fa fa-wpforms"></i>Lead Form</a></li>
                    <?php } ?>
                    <?php if ($role::checkiMenuItem($role_function, "listlwuser")) { ?>
                        <li <?php echo ($this->dispatcher->getControllerName() === "listlwuser") ? $menu_active : ""; ?> ><a
                                    href="<?php echo $this->url->get("/list-lw-user"); ?>"><i
                                        class="fa fa-user-plus"></i>Lw User</a></li>
                    <?php } ?>
                    <?php if ($role::checkiMenuItem($role_function, "sentemaillog")) { ?>
                        <li <?php echo ($this->dispatcher->getControllerName() === "sentemaillog") ? $menu_active : ""; ?> ><a
                                    href="<?php echo $this->url->get("/list-email-log"); ?>"><i
                                        class="fa fa-book"></i>Email Log</a></li>
                    <?php } ?>
                    <?php if ($role::checkiMenuItem($role_function, "contactus")) { ?>
                        <li <?php echo ($this->dispatcher->getControllerName() === "contactus") ? $menu_active : ""; ?> ><a
                                    href="<?php echo $this->url->get("/list-contactus"); ?>"><i
                                        class="fa fa-envelope"></i>Contact us</a></li>
                    <?php } ?>
                    <?php if ($role::checkiMenuItem($role_function, "payment")) { ?>
                        <li <?php echo ($this->dispatcher->getControllerName() == "payment") ? $menu_active : ""; ?>><a
                                    href="<?php echo $this->url->get("/list-make-payment"); ?>"><i
                                        class="fa fa-money"></i>Make
                                Payment</a></li>
                    <?php } ?>
                    <?php if($check_translate){ ?>
                        <li <?php echo ($check_translate_sub)?$menu_active:""; ?> ><a><i class="fa fa-language"></i> Translate <span class="fa fa-chevron-down"></span></a>
                            <ul class="nav child_menu" <?php echo ($check_translate_sub)?$menu_sub_active:""; ?> >
                                <?php if($role::checkiMenuItem($role_function,"translate")) { ?>
                                    <li <?php echo ($this->dispatcher->getControllerName() === "translate")?$menu_sub_sub_active:""; ?> >
                                        <a href="<?php echo $this->url->get("/list-translate");?>">Cron Translate</a>
                                    </li>
                                <?php } ?>
                                <?php if($role::checkiMenuItem($role_function,"tooltranslate")) { ?>
                                    <li <?php echo ($this->dispatcher->getControllerName() === "tooltranslate")?$menu_sub_sub_active:""; ?> >
                                        <a href="<?php echo $this->url->get("/tool-translate");?>">Tool Translate</a>
                                    </li>
                                <?php } ?>

                                <?php if ($role::checkiMenuItem($role_function, "tooltranslatetable")) { ?>
                                    <li <?php echo ($this->dispatcher->getControllerName() === "tooltranslatetable") ? $menu_sub_sub_active : ""; ?> >
                                        <a href="<?php echo $this->url->get("/tool-translate-table");?>">Tool Translate table</a>
                                    </li>
                                <?php } ?>
                                <?php if ($role::checkiMenuItem($role_function, "translatehistory")) { ?>
                                    <li <?php echo ($this->dispatcher->getControllerName() === "translatehistory") ? $menu_sub_sub_active : ""; ?> >
                                        <a href="<?php echo $this->url->get("/list-translate-history");?>">Translate History</a>
                                    </li>
                                <?php } ?>

                            </ul>
                        </li>
                    <?php } ?>
                    <?php if($role::checkiMenuItem($role_function,"deletecachetool")) { ?>
                        <li <?php echo ($this->dispatcher->getControllerName() === "deletecachetool")?$menu_sub_sub_active:""; ?>><a href="<?php echo $this->url->get("/delete-cache-tool");?>"><i class="fa fa-bug"></i>Delete Cache</a></li>
                    <?php } ?>
                </ul>
            </div>
        </div>
        <!-- /sidebar menu -->
    </div>
</div>