<?php
$urlPage = "?id=".$cron_id;
if(strlen($this->dispatcher->getParam("txtSearch"))> 0){
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtSearch" => $this->dispatcher->getParam("txtSearch")));
}
if(strlen($this->dispatcher->getParam("txtTable"))> 0){
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtTable" => $this->dispatcher->getParam("txtTable")));
}
if (strlen($this->dispatcher->getParam("lang_code")) > 0) {
    if ($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("slLanguage" => $this->dispatcher->getParam("lang_code")));
}
if(strlen($this->dispatcher->getParam("txtFrom")) > 0) {
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtFrom" => $this->dispatcher->getParam("txtFrom")));
}
if(strlen($this->dispatcher->getParam("txtTo")) > 0) {
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtTo" => $this->dispatcher->getParam("txtTo")));
}
?>

<div class="page-title">
    <div class="title_left">
        <h3>Detail: Cron ID = <?=$cron_id?></h3>
    </div>
</div>
<?php if(isset($msg_result))  {?>
    <div class="clearfix"></div>
    <div  class="alert alert-<?php echo $msg_result['status']?> alert-dismissible fade in" role="alert">
        <?php echo $msg_result['msg']; ?>
    </div>
<?php } ?>
<?php $message_success = isset($msg_del["success"])? $msg_del["success"] :'';
$message_error = isset($msg_del["error"])? $msg_del["error"] :'';
if(!empty($message_success)) { ?>
    <div class="clearfix"></div>
    <div  class="alert alert-success alert-dismissible fade in" role="alert">
        <?php echo $message_success; ?>
    </div>
<?php }if(!empty($message_error)) { ?>
    <div class="clearfix"></div>
    <div  class="alert alert-error alert-dismissible fade in" role="alert">
        <?php echo $message_error; ?>
    </div>
<?php } ?>
<div class="clearfix"></div>
<form class="searchForm" name="form-cron-detail" method="post" action="">
    <?php $keyword = $this->dispatcher->getParam("txtSearch");
    $from = $this->dispatcher->getParam("txtFrom");
    $to = $this->dispatcher->getParam("txtTo");
    ?>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <div class="row ">
                        <div class="col-md-1">
                            <h2 class="">Keyword</h2>
                        </div>
                        <div class="col-md-3">
                            <input maxlength="255" class="form-control" type="text" name="txtSearch" placeholder="ID,Table" value="<?php echo isset($keyword) ? $keyword : ""; ?>">
                        </div>
                        <div class="col-md-1">
                            <h2 class="">Language</h2>
                        </div>
                        <div class="col-md-3">
                            <select class="form-control" name="slLanguage" id="slLanguage">
                                <option value="">All Language</option>
                                <?php echo isset($slLanguage) ? $slLanguage : '' ?>
                            </select>
                        </div>
                        <div class="clearfix" style="margin: 20px"></div>
                        <div class="col-md-1">
                            <h2>From date</h2>
                        </div>
                        <div class="col-md-3">
                            <input name="txtFrom" id="txtFrom" autocomplete="off" type="text" class="form-control datepicker-here" data-timepicker="true" data-time-format='hh:ii' placeholder="From Date" value="<?php echo isset($from) ? $from : ''; ?>" >
                        </div>
                        <div class="col-md-1">
                            <h2>To date</h2>
                        </div>
                        <div class="col-md-3">
                            <input name="txtTo" id="txtTo" autocomplete="off" type="text" class="form-control datepicker-here" data-timepicker="true" data-time-format='hh:ii' placeholder="To Date" value="<?php echo isset($to) ? $to : ''; ?>" >
                        </div>
                        <div class="col-md-1">
                            <button type="button" name="search" class="btn btn-success">Search</button>
                        </div>
                        <div class="col-md-1">
                            <a class="btn btn-primary" href="list-translate">Back</a>
                        </div>
                    </div>
                    <div >
                        <strong>Total</strong>
                        <?php echo $list_cron_detail->total_items ?> records
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered">
                            <thead class="table_header" >
                            <tr class="headings">
                                <th width="5%" class="column-title">ID </th>
                                <th width="15%" class="column-title">Table </th>
                                <th width="5%" class="column-title">Language </th>
                                <th width="50%" class="column-title">ID success</th>
                                <th width="30%" class="column-title">ID error</th>
                                <th width="5%" class="column-title">Total </th>
                                <th width="10%" class="column-title">Insert time </th>
                                <th width="5%" class="column-title">Active </th>
                            </tr>
                            </thead>
                            <?php /** @var \Forexceccom\Models\ForeccecCronDetail $item */?>
                            <tbody class="tb_body">
                            <?php foreach ($list_cron_detail->items as $item) { ?>
                                <tr >
                                    <td class="text-center"><?php echo $item->getDetaiId() ?></td>
                                    <td><?php echo $item->getDetailTable() ?></td>
                                    <td class="text-center"><?php echo $item->getDetailLangCode() ?></td>
                                    <td><textarea style="width: 100%"><?php echo $item->getDetailData() ?></textarea></td>
                                    <td><textarea style="width: 100%"><?php echo $item->getDetailDataError() ?></textarea></td>
                                    <td class="text-center"><?php echo $item->getDetailTotal() ?></td>
                                    <td><?php echo $this->my->formatDateTime($item->getDetailInsertTime(),false) ?></td>

                                    <td class="text-center" data-title="Active">
                                        <?php
                                        $status = $item->getDetailActive();
                                        $classStatus = ($status == "Y") ? "success" : "danger" ;
                                        ?>
                                        <span class="label label-<?php echo $classStatus; ?>"><?php echo $status; ?></span>
                                    </td>
                                </tr>
                            <?php }?>
                            </tbody>
                        </table>
                    </div>
                    <div class="clearfix"></div>
                    <div class="row">
                        <div class="col-md-6 "></div>
                        <div class="col-md-6">
                            <?php if($list_cron_detail->total_pages > 1) {?>
                                <nav class="paginate-footer">
                                    <?php  if($urlPage != "?") $urlPage .= "&";
                                    $urlPage .= "page=";
                                    echo $this->my->renderPagination($urlPage, $list_cron_detail->current, $list_cron_detail->total_pages, 2);
                                    ?>
                                </nav>
                            <?php }?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script>
    $(document).ready(function(){
        $('button[name=search]').click(function() {
            $('form[name=form-cron-detail]').prop('action','<?php echo $this->url->get('/detail-cron?id='.$cron_id); ?>');
            $('form[name=form-cron-detail]').submit();
        });
    });
</script>