<?php
$urlPage = "?";
if(strlen($this->dispatcher->getParam("txtSearch"))> 0){
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtSearch" => $this->dispatcher->getParam("txtSearch")));
}
?>
<div class="page-title">
    <div class="title_left">
        <h3>Cron</h3>
    </div>
</div>
<?php if(isset($msg_result))  {?>
<div class="clearfix"></div>
<div  class="alert alert-<?php echo $msg_result['status']?> alert-dismissible fade in" role="alert">
    <?php echo $msg_result['msg']; ?>
</div>
<?php } ?>
<?php $message_success = isset($msg_del["success"])? $msg_del["success"] :'';
$message_error = isset($msg_del["error"])? $msg_del["error"] :'';
if(!empty($message_success)) { ?>
    <div class="clearfix"></div>
    <div  class="alert alert-success alert-dismissible fade in" role="alert">
        <?php echo $message_success; ?>
    </div>
<?php }if(!empty($message_error)) { ?>
    <div class="clearfix"></div>
    <div  class="alert alert-error alert-dismissible fade in" role="alert">
        <?php echo $message_error; ?>
    </div>
<?php } ?>
<div class="clearfix"></div>
<form class="searchForm" name="form-cron" method="post" action="">
    <?php $keyword = $this->dispatcher->getParam("txtSearch");
    ?>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <div class="row ">
                        <div class="col-md-1">
                            <h2 class="">Keyword</h2>
                        </div>
                        <div class="col-md-4">
                            <input maxlength="255" class="form-control" type="text" name="txtSearch" placeholder="ID, Name, Code" value="<?php echo isset($keyword) ? $keyword : ""; ?>">
                        </div>
                        <div class="col-md-1">
                            <button type="button" name="search" class="btn btn-success">Search</button>
                        </div>
                    </div>
                    <div >
                        <strong>Total</strong>
                        <?php echo $list_cron->total_items ?> records
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered">
                            <thead class="table_header" >
                            <tr class="headings">
                                <th width="5%" class="column-title">ID </th>
                                <th width="15%" class="column-title">Type </th>
                                <th width="10%" class="column-title">Status</th>
                                <th width="20%" class="column-title">User </th>
                                <th width="15%" class="column-title">Total time run</th>
                                <th width="15%" class="column-title">Insert time </th>
                                <th width="5%" class="column-title">Active </th>
                                <th width="6%" class="column-title no-link last"><span class="nobr">Action</span></th>
                            </tr>
                            </thead>
                            <?php /** @var \Forexceccom\Models\ForexcecCron $item */?>
                            <tbody class="tb_body">
                            <?php foreach ($list_cron->items as $item) { ?>
                                <tr >
                                    <td class="text-center"><?php echo $item->getCronId() ?></td>
                                    <td><?php echo $item->getCronType() ?></td>
                                    <td class="text-center"><?php echo $item->getCronStatus() ?></td>
                                    <td><?php echo $item->getCronUser() ?></td>
                                    <td class="text-center"><?php echo date('H:i:s',$item->getCronTotalTime()) ?></td>
                                    <td><?php echo $this->my->formatDateTime($item->getCronInsertTime(),false) ?></td>
                                    <td>
                                        <?php
                                        $status = $item->getCronActive();
                                        $classStatus = ($status == "Y") ? "success" : "danger" ;
                                        ?>
                                        <span class="label label-<?php echo $classStatus; ?>"><?php echo $status; ?></span>
                                    </td>
                                    <td class="text-center"><a class="btn btn-primary btn-xs margin-0" href="<?php echo $this->url->get("/detail-cron?id=").$item->getCronId(); ?>">Detail</a>
                                    </td>
                                </tr>
                            <?php }?>
                            </tbody>
                        </table>
                    </div>
                    <div class="clearfix"></div>
                    <div class="row">
                        <div class="col-md-6 "></div>
                        <div class="col-md-6">
                            <?php if($list_cron->total_pages > 1) {?>
                                <nav class="paginate-footer">
                                    <?php  if($urlPage != "?") $urlPage .= "&";
                                    $urlPage .= "page=";
                                    echo $this->my->renderPagination($urlPage, $list_cron->current, $list_cron->total_pages, 2);
                                    ?>
                                </nav>
                            <?php }?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script>
    $(document).ready(function(){
        $('button[name=search]').click(function() {
            $('form[name=form-cron]').prop('action','<?php echo $this->url->get('/list-cron'); ?>');
            $('form[name=form-cron]').submit();
        });
    });
</script>