<?php
/**
 * @var \Forexceccom\Models\ForexcecListLwUser $model
 */
?>
<div class="page-title">
    <div class="title_left">
        <h3 class="type-title">List LW User Detail #<?=$model->getForexcecPubUserId() ?></h3>
    </div>
</div>
<div class="clearfix"></div>
<p id="alertSubscribe"></p>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br />
                <h3>List LW User Information:</h3>

                <table class="table table-hover table-striped table-responsive table-bordered table-activity">
                    <tbody>
                    <tr>
                        <td style="width: 250px" >User Name</td>
                        <td><?= $model->getForexcecRealName(); ?></td>
                    </tr>
                    <tr>
                        <td>User Email</td>
                        <td><?= $model->getForexcecEmail(); ?></td>
                    </tr>
                    <tr>
                        <td>Account ID</td>
                        <td><?=  str_replace(',',', ',$model->getForexcecAccount()) ; ?></td>
                    </tr>
                    <tr>
                        <td>Is Enable</td>
                        <td>
                            <?php $class_checked = ($model->getForexcecIsEnable() == 'true') ? 'success' : 'danger' ; ?>
                            <span class="badge badge-<?= $class_checked; ?>"><?= $model->getForexcecIsEnable(); ?></span>
                        </td>
                    </tr>
                    <tr>
                        <td>Last Login Time</td>
                        <td><?= $model->getForexcecLastLoginTime() ? $this->my->formatDateTime(($model->getForexcecLastLoginTime()),false) : ""; ?></td>
                    </tr>
                    <tr>
                        <td>Register Time</td>
                        <td><?= $this->my->formatDateTime($model->getForexcecRegisterTime(),false); ?></td>
                    </tr>
                    <?php
                    use \Forexceccom\Repositories\SentEmailLog;
                    use \Forexceccom\Models\ForexcecSentEmailLog;
                    $log_email = SentEmailLog::findFirstByEmail($model->getForexcecEmail(),ForexcecSentEmailLog::FORM_LW_USER);
                    $is_subscribe = $log_email ? $log_email->getSentIsSubscribe() : "";
                    $select_subscribe = SentEmailLog::getComboboxSubscribe($is_subscribe);
                    ?>
                    <tr>
                        <td>Is Subscribe</td>
                        <td>
                            <select id="slSubscribe" name="slSubscribe" style="width: 50px">
                                <?= isset($select_subscribe) ? $select_subscribe : "" ?>
                            </select>
                        </td>
                    </tr>
                    </tbody>
                    </table>
                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-1">
                    <a class="btn btn-primary" href="<?= $this->url->get("/list-lw-user"); ?>">Back List</a>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $('#slSubscribe').on('change',function () {
        var is_subscribe = $('#slSubscribe').val();
        var email = "<?=$model->getForexcecEmail()?>";
        $.ajax({
            url: "<?php echo $this->url->get('/change-is-subscribe'); ?>",
            type: 'POST',
            dataType: "JSON",
            data: {is_subscribe: is_subscribe, email: email},
            success: function (data) {
                if (data.status == 'success') {
                    $('#alertSubscribe').addClass('alert alert-success');
                    $('#alertSubscribe').html('Change Subscribe success.');
                } else {
                    $('#alertSubscribe').addClass('alert alert-danger');
                    $('#alertSubscribe').html(data.message);
                }
            }
        });
    })
</script>

