<script>
    $(document).ready(function () {
        $('form[name=type-form]').submit(function (event) {
            var valid = true;
            if ($('input[name=txtKeyword]').val() == '') {
                $('.msg-keyword').text('Keyword field is required.');
                $('#txtKeyword').addClass("border-red");
                valid = false;
            } else {
                $('.msg-keyword').text('');
                $('#txtKeyword').removeClass("border-red");
            }
            if ($('input[name=txtOrder]').val() == '') {
                $('.msg-order').text('Order field is required.');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else if (isNaN($('input[name=txtOrder]').val())) {
                $('.msg-order').text('Enter a valid order.');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else {
                $('.msg-order').text('');
                $('#txtOrder').removeClass("border-red");
            }
            if (!valid) event.preventDefault();
            if (valid) {
                $('button[name=sbmType]').prop('disabled', true);
            }
        });
        function call(id, tableName, langSuccess, locationSuccess, statusInsertEn = false, statusInsertLang = false) {
            $.ajax({
                url: "<?php echo $this->url->get("/insert-data-translate")?>",
                cache: false,
                type: "POST",
                dataType: "JSON",
                data: {
                    'id': id,
                    'table': tableName,
                    'langSuccess': langSuccess,
                    'locationSuccess': locationSuccess,
                    'statusInsertEn': statusInsertEn,
                    'statusInsertLang': statusInsertLang
                },
                success: function (data) {
                    if (data.status === 'processing') {
                        $('#percent').html(data.percent + '%');
                        call(data.id, data.table, data.langSuccess, data.locationSuccess, data.statusInsertEn, data.statusInsertLang);
                    }  else if (data.status === 'errorAPI') {
                        $('#loading').hide();
                        $('#alertInsertTranslateError').show();
                        $('#alertInsertTranslateError').html(data.message);
                    } else {
                        $('#insertMultiTranslate').hide();
                        $('#loading').hide();
                        $('#alertInsertTranslate').show();
                        $('input[name=radActive]:nth-child(1)').attr('checked', true);
                    }
                }
            });
        }
        $("#insertMultiTranslate").on('click', function () {
            $('#alertInsertTranslateError').hide();
            $('#alertInsertTranslate').hide();
            $('#loading').show();
            var id = <?= $formData['type_id'] ?>;
            var tableName = 'forexcec_type';
            var langSuccess = [];
            var locationSuccess = [];
            call(id, tableName, langSuccess,locationSuccess);
            $("#insertMultiTranslate").prop('disabled', true);
        });
    });
</script>
<div class="page-title">
    <div class="title_left">
        <h3 class="type-title">Type</h3>
    </div>
</div>
<div class="clearfix"></div>
<?php if (!empty($messages['message'])) {
    ?>
    <div class="clearfix"></div>
    <p style="font-size:18px;text-align:center" class="alert alert-<?php echo $messages['typeMessage'] ?>">
        <?php echo $messages['message']; ?>
    </p>
<?php } ?>

<div id="loading" hidden
     style="position: fixed;z-index: 10000;top: 0px;left: 0px;width: 100%;height: 100%;background: #fff;filter: alpha(opacity=85);opacity: 1;background: rgba(255, 255,255,0);text-align: center; color:#f00;">
    <div style="background-color: #FDF7CC;border: 1px solid #FDC86C;border-radius: 4px;padding: 1px;margin: 20px auto;width: 50%;">
        <img src="<?php echo $this->url->getStatic('backend/img/waiting.gif'); ?>"
             alt='<?php echo htmlentities(defined('txt_processing') ? txt_processing : ''); ?>'
             title='<?php echo htmlentities(defined('txt_processing') ? txt_processing : ''); ?>'
             style="vertical-align:middle;position: relative;z-index: 10001;"/><?php echo defined('txt_processing') ? txt_processing : ''; ?>
        <span id="percent">0%</span>. Please waiting for the system to run!
    </div>
</div>
<div class="clearfix"></div>
<p id="alertInsertTranslate" hidden style="font-size:18px;text-align:center" class="alert alert-success">
    Update & Translate Content Type success
</p>
<p id="alertInsertTranslateError" hidden style="font-size:18px;text-align:center" class="alert alert-danger"></p>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">Form Edit
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br/>
                <form name="type-form" id="type-form" data-parsley-validate class="form-horizontal form-label-left"
                      method="post">
                    <input type="hidden" name="save" id="save" value="general"/>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Location Country <span
                                    class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <select disabled class="form-control" name="slcLocationCountry"
                                    id="slcLocationCountry">
                                <?php
                                echo isset($select_location_country) ? $select_location_country : "";
                                ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Type </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <select id="slcType" name="slcType" class="form-control col-md-7 col-xs-12" required>
                                <option value=0>Select Type...</option>
                                <?php
                                echo isset($select_type) ? $select_type : "";
                                ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Keyword <span
                                    class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255"
                                   value="<?php echo isset($formData["type_keyword"]) ? $formData["type_keyword"] : "" ?>"
                                   id="txtKeyword" name="txtKeyword"
                                   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["keyword"])) ? $messages["status"] : ""; ?>"
                                   type="text">
                            <span class="text-danger msg-keyword"><?php echo isset($messages["keyword"]) ? $messages["keyword"] : ""; ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Meta image</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255"
                                   value="<?php echo isset($formData["type_meta_image"]) ? $formData["type_meta_image"] : "" ?>"
                                   type="text" id="txtMetaImage" name="txtMetaImage"
                                   class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Order <span
                                    class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="5"
                                   value="<?php echo isset($formData["type_order"]) ? $formData["type_order"] : "" ?>"
                                   id="txtOrder" name="txtOrder"
                                   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["order"])) ? $messages["status"] : ""; ?>"
                                   type="text">
                            <span class="text-danger msg-order"><?php echo isset($messages["order"]) ? $messages["order"] : ""; ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Icon</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255"
                                   value="<?php echo isset($formData["type_icon"]) ? $formData["type_icon"] : "" ?>"
                                   type="text" id="txtIcon" name="txtIcon"
                                   class="form-control col-md-7 col-xs-12">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Active</label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radActive"
                                                                  value="Y" <?php echo (isset($formData["type_active"]) && $formData["type_active"] == "Y") ? "checked" : ''; ?>>Yes<span
                                        class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radActive"
                                                                  value="N" <?php echo (isset($formData["type_active"]) && $formData["type_active"] == "N") ? "checked" : ''; ?>>No<span
                                        class="checkmark"></span></label>
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button id="sbmType" name="sbmType" type="submit" class="btn btn-success">Save change
                            </button>
                            <a class="btn btn-primary"
                               href="<?php echo $this->url->get("/list-type?slcLocationCountry=" . $location_country_code . "&slcLang=" . $formData['lang_current']); ?>">Cancel</a>
                            <?php
                            $contentArticleLang = \Forexceccom\Models\ForexcecTypeLang::findFirstById($formData['type_id']);
                            if (!$contentArticleLang) { ?>
                                <a id="insertMultiTranslate" class="btn btn-danger pull-right text-right">Insert &
                                    Translate</a>
                            <?php } ?>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <ul class="nav nav-pills" role="tablist">
                <?php
                foreach ($formData['arr_language'] as $code => $lang) {
                    $active = $formData['lang_current'] == $code ? "active" : "";
                    ?>
                    <li role="presentation" class="<?php echo $active; ?>"><a href="#<?php echo $code ?>translate"
                                                                              aria-controls="<?php echo $code ?>translate"
                                                                              role="tab"
                                                                              data-toggle="tab"><?php echo strtoupper($code) . ' - ' .
                                $lang;
                            ?></a></li>
                <?php } ?>
            </ul>
            <div class="tab-content">
                <?php foreach ($formData['arr_language'] as $code => $lang) {
                    $active = $formData['lang_current'] == $code ? "active" : "";
                    ?>
                    <div role="tabpanel" class="tab-pane <?php echo $active; ?>" id="<?php echo $code; ?>translate">
                        <br>
                        <form name="type-form<?php echo $code; ?>" id="type-form<?php echo $code; ?>"
                              data-parsley-validate class="form-horizontal form-label-left" method="post">
                            <input type="hidden" name="save" id="save" value="<?php echo $code; ?>"/>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtName">Name <span
                                            class="text-danger">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input maxlength="255"
                                           value="<?php echo isset($formData['arr_translate'][$code]["type_name"]) ? $formData['arr_translate'][$code]["type_name"] : "" ?>"
                                           type="text" id="txtName<?php echo $code; ?>" name="txtName"
                                           class="form-control col-md-7 col-xs-12 <?php echo isset($messages[$code]["name"]) ? $messages["status"] : ""; ?>">
                                    <span class="text-danger msg-name-<?php echo $code; ?>"><?php echo isset($messages[$code]["name"]) ? $messages[$code]["name"] : "" ?></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="txtTitle" class="control-label col-md-3 col-sm-3 col-xs-12">Title <span
                                            class="text-danger">*</span></label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input maxlength="255"
                                           value="<?php echo isset($formData['arr_translate'][$code]["type_title"]) ? $formData['arr_translate'][$code]["type_title"] : "" ?>"
                                           id="txtTitle<?php echo $code; ?>"
                                           class="form-control col-md-7 col-xs-12 <?php echo isset($messages[$code]["title"]) ? $messages["status"] : ""; ?>"
                                           type="text" name="txtTitle">
                                    <span class="text-danger msg-title-<?php echo $code; ?>"><?php echo isset($messages[$code]["title"]) ? $messages[$code]["title"] : "" ?></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Meta keyword <span
                                            class="text-danger">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input maxlength="255"
                                           value="<?php echo isset($formData['arr_translate'][$code]["type_meta_keyword"]) ? $formData['arr_translate'][$code]["type_meta_keyword"] : "" ?>"
                                           id="txtMetaKey<?php echo $code; ?>" name="txtMetaKey"
                                           class="form-control col-md-7 col-xs-12 <?php echo isset($messages[$code]["meta_keyword"]) ? $messages["status"] : ""; ?>"
                                           type="text">
                                    <span class="text-danger msg-metakeyword-<?php echo $code; ?>"><?php echo isset($messages[$code]["meta_keyword"]) ? $messages[$code]["meta_keyword"] : "" ?></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Meta description <span
                                            class="text-danger">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input maxlength="255"
                                           value="<?php echo isset($formData['arr_translate'][$code]["type_meta_description"]) ? $formData['arr_translate'][$code]["type_meta_description"] : "" ?>"
                                           id="txtMetaDesc<?php echo $code; ?>" name="txtMetaDesc"
                                           class="form-control col-md-7 col-xs-12 <?php echo isset($messages[$code]["meta_description"]) ? $messages["status"] : ""; ?>"
                                           type="text">
                                    <span class="text-danger msg-metadescription-<?php echo $code; ?>"><?php echo isset($messages[$code]["meta_description"]) ? $messages[$code]["meta_description"] : "" ?></span>
                                </div>
                            </div>
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                    <button id="sbmType<?php echo $code; ?>" name="sbmType<?php echo $code; ?>"
                                            type="submit" class="btn btn-success">
                                        <?php echo 'Save ' . $lang; ?>
                                    </button>
                                </div>
                            </div>
                            <script>
                                $(document).ready(function () {
                                    $('#txtName<?php echo $code; ?>').on('input', function () {
                                        var id = <?php echo isset($formData['arr_translate'][$code]["type_id"]) ? $formData['arr_translate'][$code]["type_id"] : -1;?>;
                                        if (id < 0) {
                                            var str = $(this).val();
                                            $('#txtTitle<?php echo $code; ?>').val(str);
                                            $('#txtMetaKey<?php echo $code; ?>').val(str);
                                            $('#txtMetaDesc<?php echo $code; ?>').val(str);
                                        }
                                    });
                                    $('form[name=type-form<?php echo $code; ?>]').submit(function (event) {
                                        valid = true;
                                        if ($('#txtName<?php echo $code; ?>').val() == '') {
                                            valid = false;
                                            $('.msg-name-<?php echo $code;?>').text("Name field is required.");
                                            $('#txtName<?php echo $code; ?>').addClass("border-red");
                                        } else {
                                            $('.msg-name-<?php echo $code;?>').text('');
                                            $('#txtName<?php echo $code; ?>').removeClass("border-red");
                                        }
                                        if ($('#txtTitle<?php echo $code; ?>').val() == '') {
                                            $('.msg-title-<?php echo $code; ?>').text('Title field is required.');
                                            $('#txtTitle<?php echo $code; ?>').addClass("border-red");
                                            valid = false;
                                        } else {
                                            $('.msg-title-<?php echo $code; ?>').text('');
                                            $('#txtTitle<?php echo $code; ?>').removeClass("border-red");
                                        }
                                        if ($('#txtMetaKey<?php echo $code; ?>').val() == '') {
                                            $('.msg-metakeyword-<?php echo $code; ?>').text('Meta keyword field is required.');
                                            $('#txtMetaKey<?php echo $code; ?>').addClass("border-red");
                                            valid = false;
                                        } else {
                                            $('.msg-metakeyword-<?php echo $code; ?>').text('');
                                            $('#txtMetaKey<?php echo $code; ?>').removeClass("border-red");
                                        }
                                        if ($('#txtMetaDesc<?php echo $code; ?>').val() == '') {
                                            $('.msg-metadescription-<?php echo $code; ?>').text('Meta description field is required.');
                                            $('#txtMetaDesc<?php echo $code; ?>').addClass("border-red");
                                            valid = false;
                                        } else {
                                            $('.msg-metadescription-<?php echo $code; ?>').text('');
                                            $('#txtMetaDesc<?php echo $code; ?>').removeClass("border-red");
                                        }
                                        if (!valid) event.preventDefault();
                                        if (valid) {
                                            $('#sbmType<?php echo $code; ?>').prop('disabled', true);
                                        }
                                    });
                                });
                            </script>
                        </form>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
</div>

