<?php
$urlPage = "?";
if (strlen($this->dispatcher->getParam("txtSearch")) > 0) {
    if ($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtSearch" => $this->dispatcher->getParam("txtSearch")));
}
if ($this->dispatcher->getParam("slcIsCorporate") != "") {
    if ($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("slcIsCorporate" => $this->dispatcher->getParam("slcIsCorporate")));
}

if ($this->dispatcher->getParam("slcArea") != "") {
    if ($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("slcArea" => $this->dispatcher->getParam("slcArea")));
}
?>
<div class="page-title">
    <div class="title_left">
        <h3>Country</h3>
    </div>
</div>
<?php if (isset($msg_result)) { ?>
    <div class="clearfix"></div>
    <div class="alert alert-<?php echo $msg_result['status'] ?> alert-dismissible fade in" role="alert">
        <?php echo $msg_result['msg']; ?>
    </div>
<?php } ?>
<?php $message_success = isset($msg_del["success"]) ? $msg_del["success"] : '';
$message_error = isset($msg_del["error"]) ? $msg_del["error"] : '';
if (!empty($message_success)) { ?>
    <div class="clearfix"></div>
    <div class="alert alert-success alert-dismissible fade in" role="alert">
        <?php echo $message_success; ?>
    </div>
<?php }
if (!empty($message_error)) { ?>
    <div class="clearfix"></div>
    <div class="alert alert-error alert-dismissible fade in" role="alert">
        <?php echo $message_error; ?>
    </div>
<?php } ?>
<div class="clearfix"></div>
<form class="searchForm" name="form-country" method="post" action="">
    <?php $keyword = $this->dispatcher->getParam("txtSearch");
    ?>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <div class="row ">
                        <div class="col-md-1">
                            <h2 class="">Keyword</h2>
                        </div>
                        <div class="col-md-2">
                            <input maxlength="255" class="form-control" type="text" name="txtSearch"
                                   placeholder="ID, Name, Nationality"
                                   value="<?php echo isset($keyword) ? $keyword : ""; ?>">
                        </div>
                        <div class="col-md-3">
                            <select class="form-control" name="slcArea" id="slcArea">
                                <option value="">All Area</option>
                                <?php echo $slcArea ?>
                            </select>
                        </div>
                        <div class="col-md-3 pull-right text-right">
                            <button type="button" name="search" class="btn btn-success">Search</button>
                            <a class="btn btn-info" href="<?php echo $this->url->get("/create-country"); ?>">Add
                                New</a>
                        </div>
                    </div>
                    <div>
                        <strong>Total</strong>
                        <?php echo $list_country->total_items ?> records
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered">
                            <thead class="table_header">
                            <tr class="headings">
                                <th style="text-align: left" width="50px"><label class="container_checkbox"><input
                                                type="checkbox" id="checkboxAll"><span
                                                class="checkmark_checkbox"></span></label></th>
                                <th width="50px" class="column-title">ID</th>
                                <th class="column-title">Name</th>
                                <th class="column-title">Area</th>
                                <th width="250px" class="column-title">Nationality</th>
                                <th width="80px" class="column-title">Code</th>
                                <th width="80px" class="column-title">Order</th>
                                <th width="80px" class="column-title">Active</th>
                                <th width="50px" class="column-title no-link last"><span class="nobr">Action</span></th>
                            </tr>
                            </thead>

                            <tbody class="tb_body">
                            <?php use General\Models\Area; ?>
                            <?php foreach ($list_country->items as $item) { ?>
                                <tr>
                                    <td><label class="container_checkbox"><input class="check" name="item[]"
                                                                                 value="<?php echo $item->getCountryId() ?>"
                                                                                 type="checkbox"><span
                                                    class="checkmark_checkbox"></span></label></td>
                                    <td class=" "><?php echo $item->getCountryId() ?></td>
                                    <td class=" "><?php echo $item->getCountryName() ?></td>
                                    <?php
                                    $area_model = Area::findFirstById($item->getCountryAreaId());
                                    $area_name = !empty($area_model) ? $area_model->getAreaName() : '';
                                    ?>
                                    <td class=" "><?php echo $area_name ?></td>
                                    <td class=" "><?php echo $item->getCountryNationality() ?></td>
                                    <td class="text-center"><?php echo $item->getCountryCode() ?></td>
                                    <td class="text-center"><?php echo $item->getCountryOrder() ?></td>
                                    <td class="text-center" data-title="Active">
                                        <?php
                                        $status = $item->getCountryActive();
                                        $classStatus = ($status == "Y") ? "success" : "danger";
                                        ?>
                                        <span class="label label-<?php echo $classStatus; ?>"><?php echo $status; ?></span>
                                    </td>
                                    <td><a class="btn btn-primary btn-xs margin-0"
                                           href="<?php echo $this->url->get("/edit-country?id=" . $item->getCountryId()); ?> ">View</a>
                                    </td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="clearfix"></div>
                    <div class="row">
                        <div class="col-md-6 ">
                            <label for="slcAction">With Selected:</label>
                            <select class="form-control" id="slcAction" name="slcAction"
                                    style="display: inline-block;width: 40%">
                                <option value="" selected>Please select</option>
                                <option value="drop">Drop</option>
                            </select>
                        </div>
                        <div class="col-md-6">
                            <?php if ($list_country->total_pages > 1) { ?>
                                <nav class="paginate-footer">
                                    <?php if ($urlPage != "?") $urlPage .= "&";
                                    $urlPage .= "page=";
                                    echo $this->my->renderPagination($urlPage, $list_country->current, $list_country->total_pages, 2);
                                    ?>
                                </nav>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script>
    $(document).ready(function () {
        $('button[name=search]').click(function () {
            $('form[name=form-country]').prop('action', '<?php echo $this->url->get('/list-country'); ?>');
            $('form[name=form-country]').submit();
        });
        $('.delete-all').click(function () {
            $('form[name=form-country]').prop('action', '<?php echo $this->url->get('/delete-country'); ?>');
            $('form[name=form-country]').submit();
        });
    });
</script>
