<script>
    $( document ).ready(function() {
        $('form[name=user-form]').submit(function(event) {
            var valid = true;
            if($('input[name=txtName]').val() == '') {
                $('.msg-name').text('Name field is required.');
                $('#txtName').addClass("border-red");
                valid = false;
            } else {
                $('.msg-name').text('');
                $('#txtName').removeClass("border-red");
            }
            if($('input[name=txtEmail]').val() == '') {
                $('.msg-email').text('Email field is required.');
                $('#txtEmail').addClass("border-red");
                valid = false;
            }else if(!emailValid($('input[name=txtEmail]').val()) ){
                valid = false;
                $('.msg-email').text('Email is invalid.');
                $('#txtEmail').addClass("border-red");
            } else {
                $('.msg-email').text('');
                $('#txtEmail').removeClass("border-red");
            }
            if($('input[name=txtPassword]').val() == '') {
                $('.msg-password').text('Password field is required.');
                $('#txtPassword').addClass("border-red");
                valid = false;
            } else {
                $('.msg-password').text('');
                $('#txtPassword').removeClass("border-red");
            }
            if ($('select[name=slcRole]').val() == '-1') {
                $('.msg-role').text('Role field is required.');
                $('#slcRole').addClass("border-red");
                valid = false;
            } else {
                $('.msg-role').text('');
                $('#slcRole').removeClass("border-red");
            }
            if( ! valid ) event.preventDefault();
            if( valid ) {
                $('button[name=sbmUser]').prop('disabled', true);
            }
        });

        function emailValid(email) {
            var re = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
            return re.test(email);
        };
    })
</script>

<div class="page-title">
    <div class="title_left">
        <h3 class="type-title">User</h3>
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">Form Create
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br />
                <form name="user-form" id="user-form" data-parsley-validate class="form-horizontal form-label-left" method="post">
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtName">Name <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($oldinput["name"]) ? $oldinput["name"] : "" ?>" type="text" id="txtName" name="txtName" class="form-control col-md-7 col-xs-12 <?php echo isset($messages["name"]) ? $messages["status"] : ""; ?>">
                            <span class="text-danger msg-name"><?php echo isset($messages["name"]) ? $messages["name"] : ""?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtEmail">Email <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($oldinput["email"]) ? $oldinput["email"] : "" ?>" type="text" id="txtEmail" name="txtEmail" class="form-control col-md-7 col-xs-12 <?php echo isset($messages["email"]) ? $messages["status"] : ""; ?>">
                            <span class="text-danger msg-email"><?php echo isset($messages["email"]) ? $messages["email"] : ""?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtPassword">Password <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($oldinput["password"]) ? $oldinput["password"] : "" ?>" type="text" id="txtPassword" name="txtPassword" class="form-control col-md-7 col-xs-12 <?php echo isset($messages["password"]) ? $messages["status"] : ""; ?>">
                            <span class="text-danger msg-password"><?php echo isset($messages["password"]) ? $messages["password"] : ""?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="txtTitle" class="control-label col-md-3 col-sm-3 col-xs-12">Role Type <span class="text-danger">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <select id="slcRole" name="slcRole" class="form-control col-md-7 col-xs-12 <?php echo isset($messages["role_id"]) ? $messages["status"] : ""; ?>" required>
                                <option value = '-1' >Select Role...</option>
                                <?php
                                echo isset($slcRole) ? $slcRole : "";
                                ?>
                            </select>
                            <span class="text-danger msg-role"><?php echo isset($messages["role_id"]) ? $messages["role_id"] : ""?></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Active</label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radActive" value="Y" <?php echo (isset($oldinput["active"]) && $oldinput["active"]=="Y" )  ? "checked" : '' ; ?>>Yes<span class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radActive" value="N" <?php echo (isset($oldinput["active"]) && $oldinput["active"]=="N" )  ? "checked" : '' ; ?>>No<span class="checkmark"></span></label>
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button name="sbmUser" type="submit" class="btn btn-success">Save change</button>
                            <a class="btn btn-primary" href="<?php echo $this->url->get("/list-user"); ?>">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>