<script>
    $(document).ready(function () {
        var id = <?php echo $oldinput["id"]; ?>;
        $('#txtName').on('input', function () {
            var str = $(this).val();
            if (id == -1) {
                var str_slug = slugify(str);
                $('#txtKeyword').val(str_slug);
                $('#txtTitle').val(str);
                $('#txtMetakey').val(str);
                $('#txtMetades').val(str);
            }
        });
        if (id > -1) {
            $('input[name=txtKeyword]').attr('readonly', true);
        }
        $('form[name=type-form]').submit(function (event) {
            var valid = true;
            if ($('input[name=txtName]').val() == '') {
                $('.msg-name').text('Name field is required.');
                $('#txtName').addClass("border-red");
                valid = false;
            } else {
                $('.msg-name').text('');
                $('#txtName').removeClass("border-red");
            }
            if ($('input[name=txtTitle]').val() == '') {
                $('.msg-title').text('Title field is required.');
                $('#txtTitle').addClass("border-red");
                valid = false;
            } else {
                $('.msg-title').text('');
                $('#txtTitle').removeClass("border-red");
            }
            if ($('textarea[name=txtMetakey]').val() == '') {
                $('.msg-metakeyword').text('Meta keyword field is required.');
                $('#txtMetakey').addClass("border-red");
                valid = false;
            } else {
                $('.msg-metakeyword').text('');
                $('#txtMetakey').removeClass("border-red");
            }
            if ($('textarea[name=txtMetades]').val() == '') {
                $('.msg-metadescription').text('Meta description field is required.');
                $('#txtMetades').addClass("border-red");
                valid = false;
            } else {
                $('.msg-metadescription').text('');
                $('#txtMetades').removeClass("border-red");
            }
            if ($('input[name=txtKeyword]').val() == '') {
                $('.msg-keyword').text('Keyword field is required.');
                $('#txtKeyword').addClass("border-red");
                valid = false;
            } else {
                $('.msg-keyword').text('');
                $('#txtKeyword').removeClass("border-red");
            }
            if (!valid) event.preventDefault();
            if (valid) {
                $('button[name=sbmType]').prop('disabled', true);
            }
        });
    });
</script>
<?php
$country_code = isset($country_code) ? $country_code : '';
?>
<div class="page-title">
    <div class="title_left">
        <h3 class="type-title">Page</h3>
    </div>
</div>
</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">Form Create
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br/>
                <form name="type-form" id="type-form" data-parsley-validate class="form-horizontal form-label-left"
                      method="post">
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtName">Name <span
                                    class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255"
                                   value="<?php echo isset($oldinput["name"]) ? $oldinput["name"] : "" ?>" type="text"
                                   id="txtName" name="txtName"
                                   class="form-control col-md-7 col-xs-12 <?php echo isset($messages["name"]) ? $messages["status"] : ""; ?>">
                            <span class="text-danger msg-name"><?php echo isset($messages["name"]) ? $messages["name"] : "" ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="txtTitle" class="control-label col-md-3 col-sm-3 col-xs-12">Title <span
                                    class="text-danger">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255"
                                   value="<?php echo isset($oldinput["title"]) ? $oldinput["title"] : "" ?>"
                                   id="txtTitle"
                                   class="form-control col-md-7 col-xs-12 <?php echo isset($messages["title"]) ? $messages["status"] : ""; ?>"
                                   type="text" name="txtTitle">
                            <span class="text-danger msg-title"><?php echo isset($messages["title"]) ? $messages["title"] : "" ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Keyword <span
                                    class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255"
                                   value="<?php echo isset($oldinput["keyword"]) ? $oldinput["keyword"] : "" ?>"
                                   id="txtKeyword" name="txtKeyword"
                                   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["keyword"]) || isset($messages["exist"])) ? $messages["status"] : ""; ?>"
                                   type="text">
                            <span class="text-danger msg-keyword"><?php echo isset($messages["keyword"]) ? $messages["keyword"] : "";
                                echo isset($messages["exist"]) ? $messages["exist"] : ""; ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Meta keyword <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea
                                    class="form-control <?php echo isset($messages["meta_keyword"]) ? $messages["status"] : ""; ?>"
                                    id="txtMetakey" name="txtMetakey"
                                    style="height: 100px;"><?php echo isset($oldinput["meta_keyword"]) ? $oldinput["meta_keyword"] : "" ?></textarea>
                            <span class="text-danger msg-metakeyword"><?php echo isset($messages["meta_keyword"]) ? $messages["meta_keyword"] : "" ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Meta description <span
                                    class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea
                                    class="form-control <?php echo isset($messages["meta_description"]) ? $messages["status"] : ""; ?>"
                                    id="txtMetades" name="txtMetades"
                                    style="height: 100px;"><?php echo isset($oldinput["meta_description"]) ? $oldinput["meta_description"] : "" ?></textarea>
                            <span class="text-danger msg-metadescription"><?php echo isset($messages["meta_description"]) ? $messages["meta_description"] : "" ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Meta image </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea class="form-control" id="txtMetaImage" name="txtMetaImage"
                                      style="height: 100px;"><?php echo isset($oldinput["meta_image"]) ? $oldinput["meta_image"] : "" ?></textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtStyle">Style </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea class="form-control" id="txtStyle" name="txtStyle"
                                      style="width: 750px;height: 212px;"><?php echo isset($oldinput["style"]) ? $oldinput["style"] : ""; ?></textarea>
                            <span class="text-danger msg-style"><?php echo isset($messages["style"]) ? $messages["style"] : "" ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtStyle">Content </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea class="form-control" id="txtContent" name="txtContent"
                                      style="width: 750px;height: 212px;"><?php echo isset($oldinput["content"]) ? $oldinput["content"] : ""; ?></textarea>
                            <span class="text-danger msg-style"><?php echo isset($messages["content"]) ? $messages["content"] : "" ?></span>
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button name="sbmType" type="submit" class="btn btn-success">Save change</button>
                            <a class="btn btn-primary"
                               href="<?php echo $this->url->get("/list-page/?slCountry=" . $country_code); ?>">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>