<script>
    $(document).ready(function () {
        $('form[name=page-form]').submit(function (event) {
            var valid = true;
            if ($('input[name=txtKeyword]').val() == '') {
                $('.msg-keyword').text('Keyword field is required.');
                $('#txtKeyword').addClass("border-red");
                valid = false;
            } else {
                $('.msg-keyword').text('');
                $('#txtKeyword').removeClass("border-red");
            }
            if (!valid) event.preventDefault();
            if (valid) {
                $('button[name=sbmPage]').prop('disabled', true);
            }
        });
        var oFCKeditor2;
        oFCKeditor2 = new FCKeditor('txtContent' + '<?= $formData['lang_current'] ?>');
        oFCKeditor2.Height = '400';
        oFCKeditor2.Width = '700';
        oFCKeditor2.ToolbarSet = "Default";
        oFCKeditor2.Basepath = '../backend/fckeditor/';
        oFCKeditor2.ReplaceTextarea();
        var list_lang = ["<?= $formData['lang_current'] ?>"];
        $('.tabLanguage').click(function (e) {
            var lang = $(this).data('lang');
            if (list_lang.indexOf(lang) == -1) {
                oFCKeditor2 = new FCKeditor('txtContent' + lang);
                oFCKeditor2.Height = '400';
                oFCKeditor2.Width = '700';
                oFCKeditor2.ToolbarSet = "Default";
                oFCKeditor2.Basepath = '../backend/fckeditor/';
                oFCKeditor2.ReplaceTextarea();
            }
            list_lang.push(lang);
        });

        function call(id, tableName, langSuccess, locationSuccess, statusInsertEn = false, statusInsertLang = false) {
            $.ajax({
                url: "<?php echo $this->url->get("/insert-data-translate")?>",
                cache: false,
                type: "POST",
                dataType: "JSON",
                data: {
                    'id': id,
                    'table': tableName,
                    'langSuccess': langSuccess,
                    'locationSuccess': locationSuccess,
                    'statusInsertEn': statusInsertEn,
                    'statusInsertLang': statusInsertLang
                },
                success: function (data) {
                    if (data.status === 'processing') {
                        $('#percent').html(data.percent + '%');
                        call(data.id, data.table, data.langSuccess, data.locationSuccess, data.statusInsertEn, data.statusInsertLang);
                    }  else if (data.status === 'errorAPI') {
                        $('#loading').hide();
                        $('#alertInsertTranslateError').show();
                        $('#alertInsertTranslateError').html(data.message);
                    } else {
                        $('#insertMultiTranslate').hide();
                        $('#loading').hide();
                        $('#alertInsertTranslate').show();
                        $('input[name=radActive]:nth-child(1)').attr('checked', true);
                    }
                }
            });
        }
        $("#insertMultiTranslate").on('click', function () {
            $('#alertInsertTranslateError').hide();
            $('#alertInsertTranslate').hide();
            $('#loading').show();
            var id = <?= $formData['page_id'] ?>;
            var tableName = 'forexcec_page';
            var langSuccess = [];
            var locationSuccess = [];
            call(id, tableName, langSuccess,locationSuccess);
            $("#insertMultiTranslate").prop('disabled', true);
        });

        $("#insertMulti").on('click', function () {
            $('#alertInsertTranslateError').hide();
            $('#alertInsertTranslate').hide();
            var id = <?= $formData['page_id'] ?>;
            $.ajax({
                url: "<?= $this->url->get("/insert-data-page")?>",
                method: "POST",
                data: {id: id },
                success: function(response){
                    console.log(response);
                    if (response == 'success') {
                        $('html').scrollTop(0);
                        $('#alertInsert').addClass('alert alert-success');
                        $('#alertInsert').text("Insert data Page success");
                        $('#insertMulti').hide();
                    } else {
                        $('#alertInsert').addClass('alert alert-error');
                        $('#alertInsert').text("Can't not insert data Page");
                    }

                }
            });
            $("#insertMulti").prop('disabled', true);
        });
    });
</script>
<div class="page-title">
    <div class="title_left">
        <h3 class="type-title">Page</h3>

    </div>
</div>
<?php if (!empty($messages['message'])) {
    ?>
    <div class="clearfix"></div>
    <p style="font-size:18px;text-align:center" class="alert alert-<?php echo $messages['typeMessage'] ?>">
        <?php echo $messages['message']; ?>
    </p>
<?php } ?>

<div id="loading" hidden style="position: fixed;z-index: 10000;top: 0px;left: 0px;width: 100%;height: 100%;background: #fff;filter: alpha(opacity=85);opacity: 1;background: rgba(255, 255,255,0);text-align: center; color:#f00;">
    <div style="background-color: #FDF7CC;border: 1px solid #FDC86C;border-radius: 4px;padding: 1px;margin: 20px auto;width: 50%;">
        <img src="<?php echo $this->url->getStatic('backend/img/waiting.gif'); ?>"
             alt='<?php echo htmlentities(defined('txt_processing') ? txt_processing : ''); ?>'
             title='<?php echo htmlentities(defined('txt_processing') ? txt_processing : ''); ?>'
             style="vertical-align:middle;position: relative;z-index: 10001;"/><?php echo defined('txt_processing') ? txt_processing : ''; ?> <span id="percent">0%</span>. Please waiting for the system to run!
    </div>
</div>
<div class="clearfix"></div>
<p id="alertInsertTranslate" hidden style="font-size:18px;text-align:center" class="alert alert-success">
    Update & Translate Page success
</p>
<p id="alertInsertTranslateError" hidden style="font-size:18px;text-align:center" class="alert alert-danger"></p>
<p id="alertInsert" style="font-size:18px;text-align:center" class=""></p>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">Form Edit
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br/>
                <form name="page-form" id="page-form" data-parsley-validate class="form-horizontal form-label-left"
                      method="post">
                    <input type="hidden" name="save" id="save"
                           value="<?php echo \Forexceccom\Models\ForexcecLanguage::GENERAL; ?>"/>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Location Country <span
                                    class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <select disabled class="form-control" name="slcLocationCountry" id="slcLocationCountry">
                                <?php
                                echo isset($select_location_country) ? $select_location_country : "";
                                ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Keyword <span
                                    class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255"
                                   value="<?php echo isset($formData["page_keyword"]) ? $formData["page_keyword"] : "" ?>"
                                   id="txtKeyword" name="txtKeyword"
                                   class="form-control col-md-7 col-xs-12 <?php echo isset($messages["keyword"]) ? $messages["status"] : ""; ?>"
                                   type="text">
                            <span class="text-danger msg-keyword"><?php echo isset($messages["keyword"]) ? $messages["keyword"] : ""; ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Meta image</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea class="form-control" id="txtMetaImage" name="txtMetaImage"
                                      style="height: 100px;"><?php echo isset($formData["page_meta_image"]) ? $formData["page_meta_image"] : "" ?></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtStyle">Style </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea class="form-control" id="txtStyle" name="txtStyle"
                                      style="width: 750px;height: 212px;"><?php echo isset($formData["page_style"]) ? $formData["page_style"] : ""; ?></textarea>
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button name="sbmPage" type="submit" class="btn btn-success">Save change</button>
                            <a class="btn btn-primary"
                               href="<?php echo $this->url->get("/list-page?slcLocationCountry=" . $location_country_code . "&slcLang=" . $formData['lang_current']); ?>">Cancel</a>
                            <?php
                            $contentArticleLang = \Forexceccom\Models\ForexcecPageLang::findFirstById($formData['page_id']);
                            if (!$contentArticleLang) { ?>
                                <a id="insertMultiTranslate" class="btn btn-danger pull-right text-right">Insert &
                                    Translate</a>
                            <?php } ?>
                            <?php $page_model_vi = \Forexceccom\Repositories\PageLang::findFirstByIdAndLang($formData['page_id'],"vn","vi");
                            if (!$page_model_vi) {
                                ?>
                                <a id="insertMulti" class="btn btn-danger pull-right text-right">Insert data Record COUNTRY/EN + VN/VI</a>
                            <?php } ?>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <ul class="nav nav-pills" role="tablist">
                <?php
                foreach ($formData['arr_language'] as $code => $lang) {
                    $active = $formData['lang_current'] == $code ? "active" : "";
                    ?>
                    <li role="presentation" class="<?php echo $active; ?>">
                        <a
                                href="#<?php echo $code ?>translate"
                                aria-controls="<?php echo $code ?>translate"
                                data-lang="<?= $code ?>"
                                class="tabLanguage"
                                role="tab"
                                data-toggle="tab"><?php echo strtoupper($code) . ' - '
                                . $lang;
                            ?></a></li>
                <?php } ?>
            </ul>
            <div class="tab-content">
                <?php foreach ($formData['arr_language'] as $code => $lang) {
                    $active = $formData['lang_current'] == $code ? "active" : "";
                    ?>
                    <div role="tabpanel" class="tab-pane <?php echo $active; ?>" id="<?php echo $code; ?>translate">
                        <br>
                        <form name="page-form<?php echo $code; ?>" id="page-form<?php echo $code; ?>" action=""
                              data-parsley-validate class="form-horizontal form-label-left" method="post">
                            <input type="hidden" name="save" id="save" value="<?php echo $code; ?>"/>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Name <span
                                            class="text-danger">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input maxlength="255"
                                           value="<?php echo isset($formData['arr_translate'][$code]["page_name"]) ? $formData['arr_translate'][$code]["page_name"] : "" ?>"
                                           type="text" id="txtName<?php echo $code; ?>" name="txtName"
                                           class="form-control col-md-7 col-xs-12 <?php echo (isset($messages[$code]["name"])) ? $messages["status"] : ""; ?>">
                                    <span class="text-danger msg-name-<?php echo $code; ?>"><?php echo isset($messages[$code]["name"]) ? $messages[$code]["name"] : ""; ?></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Title <span
                                            class="text-danger">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input maxlength="255"
                                           value="<?php echo isset($formData['arr_translate'][$code]["page_title"]) ? $formData['arr_translate'][$code]["page_title"] : "" ?>"
                                           type="text" id="txtTitle<?php echo $code; ?>" name="txtTitle"
                                           class="form-control col-md-7 col-xs-12 <?php echo (isset($messages[$code]["title"])) ? $messages["status"] : ""; ?>">
                                    <span class="text-danger msg-title-<?php echo $code; ?>"><?php echo isset($messages[$code]["title"]) ? $messages[$code]["title"] : ""; ?></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Meta keyword
                                    <span class="text-danger">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <textarea style="height: 100px;" id="txtMetaKey<?php echo $code; ?>"
                                              class="form-control <?php echo (isset($messages[$code]["meta_keyword"])) ? $messages["status"] : ""; ?>"
                                              name="txtMetaKey"><?php echo isset($formData['arr_translate'][$code]["page_meta_keyword"]) ? $formData['arr_translate'][$code]["page_meta_keyword"] : "" ?></textarea>
                                    <span class="text-danger msg-metakeyword-<?php echo $code; ?>"><?php echo isset($messages[$code]["meta_keyword"]) ? $messages[$code]["meta_keyword"] : ""; ?></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Meta
                                    description <span class="text-danger">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <textarea style="height: 100px;" id="txtMetaDesc<?php echo $code; ?>"
                                              class="form-control <?php echo (isset($messages[$code]["meta_description"])) ? $messages["status"] : ""; ?>"
                                              name="txtMetaDesc"><?php echo isset($formData['arr_translate'][$code]["page_meta_description"]) ? $formData['arr_translate'][$code]["page_meta_description"] : "" ?></textarea>
                                    <span class="text-danger msg-metadescription-<?php echo $code; ?>"><?php echo isset($messages[$code]["meta_description"]) ? $messages[$code]["meta_description"] : ""; ?></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Content
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <textarea id="txtContent<?php echo $code; ?>" class="form-control"
                                              name="txtContent"><?php echo isset($formData['arr_translate'][$code]["page_content"]) ? $formData['arr_translate'][$code]["page_content"] : "" ?></textarea>
                                </div>
                            </div>
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                    <button name="sbmPage<?php echo $code; ?>" type="submit"
                                            class="btn btn-success"><?php echo 'Save ' . $lang; ?></button>
                                </div>
                            </div>
                            <script>
                                $(document).ready(function () {
                                    $('#txtName<?php echo $code; ?>').on('input', function () {
                                        var id = <?php echo isset($formData['arr_translate'][$code]["page_id"]) ? $formData['arr_translate'][$code]["page_id"] : -1;?>;
                                        if (id < 0) {
                                            var str = $(this).val();
                                            $('#txtTitle<?php echo $code; ?>').val(str);
                                            $('#txtMetaKey<?php echo $code; ?>').val(str);
                                            $('#txtMetaDesc<?php echo $code; ?>').val(str);
                                        }
                                    });
                                    $('form[name=page-form<?php echo $code; ?>]').submit(function (event) {
                                        valid = true;
                                        if ($('#txtName<?php echo $code; ?>').val() == '') {
                                            valid = false;
                                            $('.msg-name-<?php echo $code;?>').text("Name field is required.");
                                            $('#txtName<?php echo $code; ?>').addClass("border-red");
                                        } else {
                                            $('.msg-name-<?php echo $code;?>').text('');
                                            $('#txtName<?php echo $code; ?>').removeClass("border-red");
                                        }
                                        if ($('#txtTitle<?php echo $code; ?>').val() == '') {
                                            $('.msg-title-<?php echo $code; ?>').text('Title field is required.');
                                            $('#txtTitle<?php echo $code; ?>').addClass("border-red");
                                            valid = false;
                                        } else {
                                            $('.msg-title-<?php echo $code; ?>').text('');
                                            $('#txtTitle<?php echo $code; ?>').removeClass("border-red");
                                        }
                                        if ($('#txtMetaKey<?php echo $code; ?>').val() == '') {
                                            $('.msg-metakeyword-<?php echo $code; ?>').text('Meta keyword field is required.');
                                            $('#txtMetaKey<?php echo $code; ?>').addClass("border-red");
                                            valid = false;
                                        } else {
                                            $('.msg-metakeyword-<?php echo $code; ?>').text('');
                                            $('#txtMetaKey<?php echo $code; ?>').removeClass("border-red");
                                        }
                                        if ($('#txtMetaDesc<?php echo $code; ?>').val() == '') {
                                            $('.msg-metadescription-<?php echo $code; ?>').text('Meta description field is required.');
                                            $('#txtMetaDesc<?php echo $code; ?>').addClass("border-red");
                                            valid = false;
                                        } else {
                                            $('.msg-metadescription-<?php echo $code; ?>').text('');
                                            $('#txtMetaDesc<?php echo $code; ?>').removeClass("border-red");
                                        }
                                        if (!valid) event.preventDefault();
                                        if (valid) {
                                            $('#sbmPage<?php echo $code; ?>').prop('disabled', true);
                                        }
                                    });
                                });
                            </script>
                        </form>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
</div>