<div class="page-title">
    <div class="title_left">
        <h3 class="emailtemplate-title">Email Template </h3>
    </div>
</div>

<?php if(!empty($messages['message']))
{
    ?>
    <div class="clearfix"></div>
    <p style="font-size:18px;text-align:center" class="alert alert-<?php echo $messages['typeMessage']?>">
        <?php echo $messages['message']; ?>
    </p>
<?php }	?>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">Form Edit</div>
            <div class="x_content">
                <br />
                <form class="form-horizontal well" id="emailtemplate-form" name="emailtemplate-form" action="<?php echo $this->url->get('/edit-emailtemplate?id=').$formData["email_id"]; ?>" method="POST" >
                    <input type="hidden" name="save" id="save" value="general" />
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Type <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($formData["email_type"]) ? $formData["email_type"] : "" ?>" type="text" id="txtType" name="txtType"   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["type"])) ? $messages["status"] : ""; ?>">
                            <span class="text-danger msg-type"><?php echo isset($messages["type"]) ? $messages["type"] : "";?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Status </label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radStatus" value="Y" <?php echo (isset($formData["email_status"]) && $formData["email_status"]=="Y" )  ? "checked" : '' ; ?>>Yes<span class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radStatus" value="N" <?php echo (isset($formData["email_status"]) && $formData["email_status"]=="N" )  ? "checked" : '' ; ?>>No<span class="checkmark"></span></label>
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button name="sbmEmailtemplate" type="submit"  class="btn btn-success">Save change</button>
                            <a class="btn btn-primary" href="<?php echo $this->url->get("list-emailtemplate");?>">Cancel</a>
                        </div>
                    </div>
                </form>
                <div class="well">
                    <ul class="nav nav-pills" role="tablist">
                        <?php
                        foreach ( $formData['arr_language'] as $code => $lang ){
                            $active = $formData['lang_current']== $code?"active":"";
                            ?>
                            <li role="presentation" class="<?php echo $active; ?>"><a href="#<?php echo $code ?>translate" aria-controls="<?php echo $code ?>translate" role="tab" data-toggle="tab"><?php echo $lang; ?></a></li>

                        <?php } ?>
                    </ul>
                    <div class="tab-content">
                        <?php foreach ($formData['arr_language'] as $code => $lang ) {
                            $active = $formData['lang_current']== $code?"active":"";
                            ?>
                            <div role="tabpanel" class="tab-pane <?php echo $active; ?>" id="<?php echo $code; ?>translate">
                                <br>
                                <form class="form-horizontal" id="emailtemplate-form-<?php echo $code; ?>" name="emailtemplate-form-<?php echo $code; ?>" action="<?php echo $this->url->get('/edit-emailtemplate?id=').$formData["email_id"]; ?>" method="POST" >
                                    <input type="hidden" name="save" id="save" value="<?php echo $code; ?>" />
                                    <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Subject
                                        </label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <input maxlength="255" value="<?php echo isset($formData['arr_translate'][$code]["email_subject"]) ? $formData['arr_translate'][$code]["email_subject"] : "" ?>" type="text" id="txtSubject<?php echo $code; ?>" name="txtSubject"   class="form-control col-md-7 col-xs-12">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Content
                                        </label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <textarea  id="txtContent<?php echo $code; ?>" class="form-control" name ="txtContent" style="width: 699px;height: 212px;" rows="3"  ><?php echo isset($formData['arr_translate'][$code]["email_content"]) ? $formData['arr_translate'][$code]["email_content"] : "" ?></textarea>
                                        </div>
                                    </div>
                                    <div class="ln_solid"></div>
                                    <div class="form-group ">
                                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                            <button id="sbmEmailtemplate_<?php echo $code;?>" type="submit"  class="btn btn-success">Save change</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        <?php } ?>

                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<script>
    $( document ).ready(function() {
        $('form[name=emailtemplate-form]').submit(function (event) {
            var valid = true;
            if($('input[name=txtType]').val() == '') {
                $('.msg-type').text('Type field is required.');
                $('#txtType').addClass("border-red");
                valid = false;
            } else {
                $('.msg-type').text('');
                $('#txtType').removeClass("border-red");
            }
            if( ! valid ) event.preventDefault();
            if( valid ) {
                $('button[name=sbmEmailtemplate]').prop('disabled', true);

            }
        });
    });
</script>

