<script>
    $( document ).ready(function() {
        $('form[name=banner-form]').submit(function(event) {
            var valid = true;
            if($( "select#slcController option:checked" ).val()==0) {
                $('.msg-controller').text('Controller is required.');
                $('#slcController').addClass("border-red");
                valid = false;
            } else {
                $('.msg-controller').text('');
                $('#slcController').removeClass("border-red");
            }
            if($('textarea[name=txtContent]').val() == '') {
                $('.msg-content').text('Content field is required.');
                $('#txtContent').addClass("border-red");
                valid = false;
            } else {
                $('.msg-content').text('');
                $('#txtContent').removeClass("border-red");
            }
            if($('input[name=txtOrder]').val() == '') {
                $('.msg-order').text('Order field is required.');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else if (isNaN($('input[name=txtOrder]').val())) {
                $('.msg-order').text('Enter a valid order.');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else {
                $('.msg-order').text('');
                $('#txtOrder').removeClass("border-red");
            }
            if( ! valid ) event.preventDefault();
            if( valid ) {
                $('button[name=sbmBanner]').prop('disabled', true);
            }
        });
    });
</script>

<div class="page-title">
    <div class="title_left">
        <h3 class="banner-title">Banner </h3>
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">Form Create</div>
            <div class="x_content">
                <br />
                <form name="banner-form" id="banner-form" action="<?php echo $this->url->get('/create-banner'); ?>" data-parsley-validate class="form-horizontal form-label-left" method="post">
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Controller <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <select id="slcController" name="slcController" class="form-control col-md-7 col-xs-12  <?php echo (isset($messages["controller"])) ? $messages["status"] : ""; ?>" >
                                <option value="">Select Controller...</option>
                                <?php echo isset($select_controller)? $select_controller : ''?>
                            </select>
                            <span class="text-danger msg-controller"><?php echo isset($messages["controller"]) ? $messages["controller"] : "";?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Image</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($formData["banner_image"]) ? $formData["banner_image"] : "" ?>" type="text" id="txtImage" name="txtImage"   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["image"])) ? $messages["status"] : ""; ?>">
                            <span class="text-danger msg-img"><?php echo isset($messages["image"]) ? $messages["image"] : "";?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Image Mobile</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($formData["banner_image_mobile"]) ? $formData["banner_image_mobile"] : "" ?>" type="text" id="txtImageMobile" name="txtImageMobile" class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["image-mobile"])) ? $messages["status"] : ""; ?>">
                            <span class="text-danger msg-img-mobile"><?php echo isset($messages["image-mobile"]) ? $messages["image-mobile"] : "";?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Title  </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($formData["banner_title"]) ? $formData["banner_title"] : "" ?>" type="text" id="txtTitle" name="txtTitle"   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["title"])) ? $messages["status"] : ""; ?>">
                            <span class="text-danger msg-title"><?php echo isset($messages["title"]) ? $messages["title"] : ""; ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Subtitle </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea class="form-control" id="txtSubtitle" name ="txtSubtitle" style="height: 112px;" ><?php echo isset($formData["banner_subtitle"]) ? $formData["banner_subtitle"] : "" ?></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Content <span class="text-danger">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea class="form-control" id="txtContent" name ="txtContent" style="height: 112px;" ><?php echo isset($formData["banner_content"]) ? $formData["banner_content"] : "" ?></textarea>
                            <span class="text-danger msg-content"><?php echo isset($messages["content"]) ? $messages["content"] : ""; ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Link</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($formData["banner_link"]) ? $formData["banner_link"] : "" ?>" type="text" id="txtLink" name="txtLink"   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["link"])  ) ? $messages["status"] : ""; ?>">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Order <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="10" value="<?php echo isset($formData["banner_order"]) ? $formData["banner_order"] : "" ?>" type="text" id="txtOrder" name="txtOrder"  class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["order"])) ? $messages["status"] : ""; ?>">
                            <span class="text-danger msg-order"><?php echo isset($messages["order"]) ? $messages["order"] : "";?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Type</label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="slcType" value="<?php echo \Forexceccom\Models\ForexcecBanner::TYPEIMAGE; ?>" <?php echo (isset($formData["banner_type"]) && $formData["banner_type"]== \Forexceccom\Models\ForexcecBanner::TYPEIMAGE)  ? "checked" : '' ; ?>><?php echo \Forexceccom\Models\ForexcecBanner::TYPEIMAGE; ?><span class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="slcType" value="<?php echo \Forexceccom\Models\ForexcecBanner::TYPEIFRAME; ?>" <?php echo (isset($formData["banner_type"]) && $formData["banner_type"]== \Forexceccom\Models\ForexcecBanner::TYPEIFRAME)  ? "checked" : '' ; ?>><?php echo \Forexceccom\Models\ForexcecBanner::TYPEIFRAME; ?><span class="checkmark"></span></label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Is Home </label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radIsHome" value="Y" <?php echo (isset($formData["banner_is_home"]) && $formData["banner_is_home"]=="Y" )  ? "checked" : '' ; ?>>Yes<span class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radIsHome" value="N" <?php echo (isset($formData["banner_is_home"]) && $formData["banner_is_home"]=="N" )  ? "checked" : '' ; ?>>No<span class="checkmark"></span></label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Active </label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radActive" value="Y" <?php echo (isset($formData["banner_active"]) && $formData["banner_active"]=="Y" )  ? "checked" : '' ; ?>>Yes<span class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radActive" value="N" <?php echo (isset($formData["banner_active"]) && $formData["banner_active"]=="N" )  ? "checked" : '' ; ?>>No<span class="checkmark"></span></label>
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button name="sbmBanner" type="submit" class="btn btn-success">Save change</button>
                            <a class="btn btn-primary" href="list-banner">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
