<div class="page-title">
    <div class="title_left">
        <h3 class="banner-title">Banner </h3>
    </div>
</div>

<?php if(!empty($messages['message']))
{
    ?>
    <div class="clearfix"></div>
    <p style="font-size:18px;text-align:center" class="alert alert-<?php echo $messages['typeMessage']?>">
        <?php echo $messages['message']; ?>
    </p>
<?php }	?>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">Form Edit</div>
            <div class="x_content">
                <br />
                <form class="form-horizontal well" id="banner-form" name="banner-form" action="<?php echo $this->url->get('/edit-banner?id=').$formData["banner_id"]; ?>" method="POST" >
                    <input type="hidden" name="save" id="save" value="general" />
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Controller <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <select id="slcController" name="slcController" class="form-control col-md-7 col-xs-12  <?php echo (isset($messages["controller"])) ? $messages["status"] : ""; ?>" >
                                <option value="">Select Controller...</option>
                                <?php echo isset($select_controller)? $select_controller : ''?>
                            </select>
                            <span class="text-danger msg-controller"><?php echo isset($messages["controller"]) ? $messages["controller"] : "";?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Link
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($formData["banner_link"]) ? $formData["banner_link"] : "" ?>" type="text" id="txtLink" name="txtLink"   class="form-control col-md-7 col-xs-12 ">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Order <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="10" value="<?php echo isset($formData["banner_order"]) ? $formData["banner_order"] : "" ?>" type="text" id="txtOrder" name="txtOrder"  class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["order"])) ? $messages["status"] : ""; ?>">
                            <span class="text-danger msg-order"><?php echo isset($messages["order"]) ? $messages["order"] : "";?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Type</label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="slcType" value="<?php echo \Forexceccom\Models\ForexcecBanner::TYPEIMAGE; ?>" <?php echo (isset($formData["banner_type"]) && $formData["banner_type"]== \Forexceccom\Models\ForexcecBanner::TYPEIMAGE)  ? "checked" : '' ; ?>><?php echo \Forexceccom\Models\ForexcecBanner::TYPEIMAGE; ?><span class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="slcType" value="<?php echo \Forexceccom\Models\ForexcecBanner::TYPEIFRAME; ?>" <?php echo (isset($formData["banner_type"]) && $formData["banner_type"]== \Forexceccom\Models\ForexcecBanner::TYPEIFRAME)  ? "checked" : '' ; ?>><?php echo \Forexceccom\Models\ForexcecBanner::TYPEIFRAME; ?><span class="checkmark"></span></label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Is Home </label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radIsHome" value="Y" <?php echo (isset($formData["banner_is_home"]) && $formData["banner_is_home"]=="Y" )  ? "checked" : '' ; ?>>Yes<span class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radIsHome" value="N" <?php echo (isset($formData["banner_is_home"]) && $formData["banner_is_home"]=="N" )  ? "checked" : '' ; ?>>No<span class="checkmark"></span></label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Active </label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radActive" value="Y" <?php echo (isset($formData["banner_active"]) && $formData["banner_active"]=="Y" )  ? "checked" : '' ; ?>>Yes<span class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radActive" value="N" <?php echo (isset($formData["banner_active"]) && $formData["banner_active"]=="N" )  ? "checked" : '' ; ?>>No<span class="checkmark"></span></label>
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button name="sbmBanner" type="submit"  class="btn btn-success">Save change</button>
                            <a class="btn btn-primary" href="<?php echo $this->url->get("list-banner");?>">Cancel</a>
                        </div>
                    </div>
                </form>
                <div class="well">
                    <ul class="nav nav-pills" role="tablist">
                        <?php
                        foreach ( $formData['arr_language'] as $code => $lang ){
                            $active = $formData['lang_current']== $code?"active":"";
                            ?>
                            <li role="presentation" class="<?php echo $active; ?>"><a href="#<?php echo $code ?>translate" aria-controls="<?php echo $code ?>translate" role="tab" data-toggle="tab"><?php echo strtoupper($code) . ' - ' . $lang; ?></a></li>

                        <?php } ?>
                    </ul>
                    <div class="tab-content">
                        <?php foreach ($formData['arr_language'] as $code => $lang ) {
                        $active = $formData['lang_current']== $code?"active":"";
                        ?>
                        <div role="tabpanel" class="tab-pane <?php echo $active; ?>" id="<?php echo $code; ?>translate">
                            <br>
                            <form class="form-horizontal" id="banner-form-<?php echo $code; ?>" name="banner-form-<?php echo $code; ?>" action="<?php echo $this->url->get('/edit-banner?id=').$formData["banner_id"]; ?>" method="POST" >
                                <input type="hidden" name="save" id="save" value="<?php echo $code; ?>" />
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Title </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input maxlength="255" value="<?php echo isset($formData['arr_translate'][$code]["banner_title"]) ? $formData['arr_translate'][$code]["banner_title"] : "" ?>" type="text" id="txtTitle<?php echo $code; ?>" name="txtTitle"   class="form-control col-md-7 col-xs-12 ">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Subtitle </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <textarea class="form-control" id="txtSubtitle<?php echo $code; ?>" name ="txtSubtitle" style="height: 112px;" ><?php echo isset($formData['arr_translate'][$code]["banner_subtitle"]) ? $formData['arr_translate'][$code]["banner_subtitle"] : "" ?></textarea>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Content <span class="text-danger">*</span></label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <textarea class="form-control" id="txtContent_<?php echo $code; ?>" name ="txtContent" style="height: 112px;" ><?php echo isset($formData['arr_translate'][$code]["banner_content"]) ? $formData['arr_translate'][$code]["banner_content"] : "" ?></textarea>
                                        <span class="text-danger msg-content_<?php echo $code; ?>"><?php echo isset($messages["content"]) ? $messages["content"] : "";?></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Image</label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input maxlength="255" value="<?php echo isset($formData['arr_translate'][$code]["banner_image"]) ? $formData['arr_translate'][$code]["banner_image"] : "" ?>" type="text" id="txtImage_<?php echo $code;?>" name="txtImage" class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["image"])) ? $messages["status"] : ""; ?>">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Image Mobile</label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input maxlength="255" value="<?php echo isset($formData['arr_translate'][$code]["banner_image_mobile"]) ? $formData['arr_translate'][$code]["banner_image_mobile"] : "" ?>" type="text" id="txtImageMobile_<?php echo $code;?>" name="txtImageMobile"   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["image-mobile"])) ? $messages["status"] : ""; ?>">
                                    </div>
                                </div>
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                        <button id="sbmBanner_<?php echo $code;?>" name="sbmBanner_<?php echo $code;?>" type="submit"  class="btn btn-success">Save change</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                            <script>
                                $(document).ready(function () {
                                    $('form[name=banner-form-<?php echo $code; ?>]').submit(function (event){
                                        var valid = true;
                                        if($('#txtContent_<?php echo $code; ?>').val() == '') {
                                            $('.msg-content_<?php echo $code; ?>').text('Content field is required.');
                                            $('#txtContent_<?php echo $code;?>').addClass("border-red");
                                            valid = false;
                                        } else {
                                            $('.msg-content_<?php echo $code; ?>').text('');
                                            $('#txtContent_<?php echo $code;?>').removeClass("border-red");
                                        }
                                        if( ! valid ) event.preventDefault();
                                        if( valid ) {
                                            $('button[name=sbmBanner_<?php echo $code;?>]').prop('disabled', true);
                                        }
                                    });

                                })
                            </script>
                        <?php } ?>

                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<script>
    $( document ).ready(function() {
        $('form[name=banner-form]').submit(function (event) {
            var valid = true;
            if($( "select#slcController option:checked" ).val()==0) {
                $('.msg-controller').text('Controller is required.');
                $('#slcController').addClass("border-red");
                valid = false;
            } else {
                $('.msg-controller').text('');
                $('#slcController').removeClass("border-red");
            }
            if($('input[name=txtOrder]').val() == '') {
                $('.msg-order').text('Order field is required.');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else if (isNaN($('input[name=txtOrder]').val())) {
                $('.msg-order').text('Enter a valid order.');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else {
                $('.msg-order').text('');
                $('#txtOrder').removeClass("border-red");
            }
            if( ! valid ) event.preventDefault();
            if( valid ) {
                $('button[name=sbmBanner]').prop('disabled', true);

            }
        });
    });
</script>

